package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AffiliatePayments generated by hbm2java
 */
public class AffiliatePayments  implements java.io.Serializable {


     private int afpId;
     private Date afpDateTime;
     private Integer afpAffiliateId;

    public AffiliatePayments() {
    }

	
    public AffiliatePayments(int afpId) {
        this.afpId = afpId;
    }
    public AffiliatePayments(int afpId, Date afpDateTime, Integer afpAffiliateId) {
       this.afpId = afpId;
       this.afpDateTime = afpDateTime;
       this.afpAffiliateId = afpAffiliateId;
    }
   
    public int getAfpId() {
        return this.afpId;
    }
    
    public void setAfpId(int afpId) {
        this.afpId = afpId;
    }
    public Date getAfpDateTime() {
        return this.afpDateTime;
    }
    
    public void setAfpDateTime(Date afpDateTime) {
        this.afpDateTime = afpDateTime;
    }
    public Integer getAfpAffiliateId() {
        return this.afpAffiliateId;
    }
    
    public void setAfpAffiliateId(Integer afpAffiliateId) {
        this.afpAffiliateId = afpAffiliateId;
    }




}


