package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * AffiliateLog generated by hbm2java
 */
public class AffiliateLog  implements java.io.Serializable {


     private int aflgId;
     private Integer aflgAffiliateId;
     private Serializable aflgReferer;
     private Serializable aflgIp;
     private Serializable aflgRequestedItem;
     private Date aflgDateTime;

    public AffiliateLog() {
    }

	
    public AffiliateLog(int aflgId) {
        this.aflgId = aflgId;
    }
    public AffiliateLog(int aflgId, Integer aflgAffiliateId, Serializable aflgReferer, Serializable aflgIp, Serializable aflgRequestedItem, Date aflgDateTime) {
       this.aflgId = aflgId;
       this.aflgAffiliateId = aflgAffiliateId;
       this.aflgReferer = aflgReferer;
       this.aflgIp = aflgIp;
       this.aflgRequestedItem = aflgRequestedItem;
       this.aflgDateTime = aflgDateTime;
    }
   
    public int getAflgId() {
        return this.aflgId;
    }
    
    public void setAflgId(int aflgId) {
        this.aflgId = aflgId;
    }
    public Integer getAflgAffiliateId() {
        return this.aflgAffiliateId;
    }
    
    public void setAflgAffiliateId(Integer aflgAffiliateId) {
        this.aflgAffiliateId = aflgAffiliateId;
    }
    public Serializable getAflgReferer() {
        return this.aflgReferer;
    }
    
    public void setAflgReferer(Serializable aflgReferer) {
        this.aflgReferer = aflgReferer;
    }
    public Serializable getAflgIp() {
        return this.aflgIp;
    }
    
    public void setAflgIp(Serializable aflgIp) {
        this.aflgIp = aflgIp;
    }
    public Serializable getAflgRequestedItem() {
        return this.aflgRequestedItem;
    }
    
    public void setAflgRequestedItem(Serializable aflgRequestedItem) {
        this.aflgRequestedItem = aflgRequestedItem;
    }
    public Date getAflgDateTime() {
        return this.aflgDateTime;
    }
    
    public void setAflgDateTime(Date aflgDateTime) {
        this.aflgDateTime = aflgDateTime;
    }




}


