package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * AttributeValuesId generated by hbm2java
 */
public class AttributeValuesId  implements java.io.Serializable {


     private Integer attribvProductId;
     private Integer attribvAttributeId;
     private Serializable attribvValue1;
     private Serializable attribvValue2;
     private Serializable attribvValue3;
     private Serializable attribvValue4;
     private Serializable attribvValue5;

    public AttributeValuesId() {
    }

    public AttributeValuesId(Integer attribvProductId, Integer attribvAttributeId, Serializable attribvValue1, Serializable attribvValue2, Serializable attribvValue3, Serializable attribvValue4, Serializable attribvValue5) {
       this.attribvProductId = attribvProductId;
       this.attribvAttributeId = attribvAttributeId;
       this.attribvValue1 = attribvValue1;
       this.attribvValue2 = attribvValue2;
       this.attribvValue3 = attribvValue3;
       this.attribvValue4 = attribvValue4;
       this.attribvValue5 = attribvValue5;
    }
   
    public Integer getAttribvProductId() {
        return this.attribvProductId;
    }
    
    public void setAttribvProductId(Integer attribvProductId) {
        this.attribvProductId = attribvProductId;
    }
    public Integer getAttribvAttributeId() {
        return this.attribvAttributeId;
    }
    
    public void setAttribvAttributeId(Integer attribvAttributeId) {
        this.attribvAttributeId = attribvAttributeId;
    }
    public Serializable getAttribvValue1() {
        return this.attribvValue1;
    }
    
    public void setAttribvValue1(Serializable attribvValue1) {
        this.attribvValue1 = attribvValue1;
    }
    public Serializable getAttribvValue2() {
        return this.attribvValue2;
    }
    
    public void setAttribvValue2(Serializable attribvValue2) {
        this.attribvValue2 = attribvValue2;
    }
    public Serializable getAttribvValue3() {
        return this.attribvValue3;
    }
    
    public void setAttribvValue3(Serializable attribvValue3) {
        this.attribvValue3 = attribvValue3;
    }
    public Serializable getAttribvValue4() {
        return this.attribvValue4;
    }
    
    public void setAttribvValue4(Serializable attribvValue4) {
        this.attribvValue4 = attribvValue4;
    }
    public Serializable getAttribvValue5() {
        return this.attribvValue5;
    }
    
    public void setAttribvValue5(Serializable attribvValue5) {
        this.attribvValue5 = attribvValue5;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AttributeValuesId) ) return false;
		 AttributeValuesId castOther = ( AttributeValuesId ) other; 
         
		 return ( (this.getAttribvProductId()==castOther.getAttribvProductId()) || ( this.getAttribvProductId()!=null && castOther.getAttribvProductId()!=null && this.getAttribvProductId().equals(castOther.getAttribvProductId()) ) )
 && ( (this.getAttribvAttributeId()==castOther.getAttribvAttributeId()) || ( this.getAttribvAttributeId()!=null && castOther.getAttribvAttributeId()!=null && this.getAttribvAttributeId().equals(castOther.getAttribvAttributeId()) ) )
 && ( (this.getAttribvValue1()==castOther.getAttribvValue1()) || ( this.getAttribvValue1()!=null && castOther.getAttribvValue1()!=null && this.getAttribvValue1().equals(castOther.getAttribvValue1()) ) )
 && ( (this.getAttribvValue2()==castOther.getAttribvValue2()) || ( this.getAttribvValue2()!=null && castOther.getAttribvValue2()!=null && this.getAttribvValue2().equals(castOther.getAttribvValue2()) ) )
 && ( (this.getAttribvValue3()==castOther.getAttribvValue3()) || ( this.getAttribvValue3()!=null && castOther.getAttribvValue3()!=null && this.getAttribvValue3().equals(castOther.getAttribvValue3()) ) )
 && ( (this.getAttribvValue4()==castOther.getAttribvValue4()) || ( this.getAttribvValue4()!=null && castOther.getAttribvValue4()!=null && this.getAttribvValue4().equals(castOther.getAttribvValue4()) ) )
 && ( (this.getAttribvValue5()==castOther.getAttribvValue5()) || ( this.getAttribvValue5()!=null && castOther.getAttribvValue5()!=null && this.getAttribvValue5().equals(castOther.getAttribvValue5()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAttribvProductId() == null ? 0 : this.getAttribvProductId().hashCode() );
         result = 37 * result + ( getAttribvAttributeId() == null ? 0 : this.getAttribvAttributeId().hashCode() );
         result = 37 * result + ( getAttribvValue1() == null ? 0 : this.getAttribvValue1().hashCode() );
         result = 37 * result + ( getAttribvValue2() == null ? 0 : this.getAttribvValue2().hashCode() );
         result = 37 * result + ( getAttribvValue3() == null ? 0 : this.getAttribvValue3().hashCode() );
         result = 37 * result + ( getAttribvValue4() == null ? 0 : this.getAttribvValue4().hashCode() );
         result = 37 * result + ( getAttribvValue5() == null ? 0 : this.getAttribvValue5().hashCode() );
         return result;
   }   


}


