package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Attributes generated by hbm2java
 */
public class Attributes  implements java.io.Serializable {


     private int attribId;
     private Serializable attribType;
     private Serializable attribName1;
     private Serializable attribName2;
     private Serializable attribName3;
     private Serializable attribName4;
     private Serializable attribName5;
     private Serializable attribLive;
     private Serializable attribFastEntry;
     private Serializable attribShowFrontend;
     private Serializable attribShowSearch;
     private Integer attribOrderByValue;
     private Serializable attribCompare;
     private Serializable attribSpecial;

    public Attributes() {
    }

	
    public Attributes(int attribId) {
        this.attribId = attribId;
    }
    public Attributes(int attribId, Serializable attribType, Serializable attribName1, Serializable attribName2, Serializable attribName3, Serializable attribName4, Serializable attribName5, Serializable attribLive, Serializable attribFastEntry, Serializable attribShowFrontend, Serializable attribShowSearch, Integer attribOrderByValue, Serializable attribCompare, Serializable attribSpecial) {
       this.attribId = attribId;
       this.attribType = attribType;
       this.attribName1 = attribName1;
       this.attribName2 = attribName2;
       this.attribName3 = attribName3;
       this.attribName4 = attribName4;
       this.attribName5 = attribName5;
       this.attribLive = attribLive;
       this.attribFastEntry = attribFastEntry;
       this.attribShowFrontend = attribShowFrontend;
       this.attribShowSearch = attribShowSearch;
       this.attribOrderByValue = attribOrderByValue;
       this.attribCompare = attribCompare;
       this.attribSpecial = attribSpecial;
    }
   
    public int getAttribId() {
        return this.attribId;
    }
    
    public void setAttribId(int attribId) {
        this.attribId = attribId;
    }
    public Serializable getAttribType() {
        return this.attribType;
    }
    
    public void setAttribType(Serializable attribType) {
        this.attribType = attribType;
    }
    public Serializable getAttribName1() {
        return this.attribName1;
    }
    
    public void setAttribName1(Serializable attribName1) {
        this.attribName1 = attribName1;
    }
    public Serializable getAttribName2() {
        return this.attribName2;
    }
    
    public void setAttribName2(Serializable attribName2) {
        this.attribName2 = attribName2;
    }
    public Serializable getAttribName3() {
        return this.attribName3;
    }
    
    public void setAttribName3(Serializable attribName3) {
        this.attribName3 = attribName3;
    }
    public Serializable getAttribName4() {
        return this.attribName4;
    }
    
    public void setAttribName4(Serializable attribName4) {
        this.attribName4 = attribName4;
    }
    public Serializable getAttribName5() {
        return this.attribName5;
    }
    
    public void setAttribName5(Serializable attribName5) {
        this.attribName5 = attribName5;
    }
    public Serializable getAttribLive() {
        return this.attribLive;
    }
    
    public void setAttribLive(Serializable attribLive) {
        this.attribLive = attribLive;
    }
    public Serializable getAttribFastEntry() {
        return this.attribFastEntry;
    }
    
    public void setAttribFastEntry(Serializable attribFastEntry) {
        this.attribFastEntry = attribFastEntry;
    }
    public Serializable getAttribShowFrontend() {
        return this.attribShowFrontend;
    }
    
    public void setAttribShowFrontend(Serializable attribShowFrontend) {
        this.attribShowFrontend = attribShowFrontend;
    }
    public Serializable getAttribShowSearch() {
        return this.attribShowSearch;
    }
    
    public void setAttribShowSearch(Serializable attribShowSearch) {
        this.attribShowSearch = attribShowSearch;
    }
    public Integer getAttribOrderByValue() {
        return this.attribOrderByValue;
    }
    
    public void setAttribOrderByValue(Integer attribOrderByValue) {
        this.attribOrderByValue = attribOrderByValue;
    }
    public Serializable getAttribCompare() {
        return this.attribCompare;
    }
    
    public void setAttribCompare(Serializable attribCompare) {
        this.attribCompare = attribCompare;
    }
    public Serializable getAttribSpecial() {
        return this.attribSpecial;
    }
    
    public void setAttribSpecial(Serializable attribSpecial) {
        this.attribSpecial = attribSpecial;
    }




}


