package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1



/**
 * AttributeValues generated by hbm2java
 */
public class AttributeValues  implements java.io.Serializable {


     private AttributeValuesId id;

    public AttributeValues() {
    }

    public AttributeValues(AttributeValuesId id) {
       this.id = id;
    }
   
    public AttributeValuesId getId() {
        return this.id;
    }
    
    public void setId(AttributeValuesId id) {
        this.id = id;
    }




}


