package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1



/**
 * CategoryHierachy generated by hbm2java
 */
public class CategoryHierachy  implements java.io.Serializable {


     private CategoryHierachyId id;

    public CategoryHierachy() {
    }

    public CategoryHierachy(CategoryHierachyId id) {
       this.id = id;
    }
   
    public CategoryHierachyId getId() {
        return this.id;
    }
    
    public void setId(CategoryHierachyId id) {
        this.id = id;
    }




}


