package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Categories generated by hbm2java
 */
public class Categories  implements java.io.Serializable {


     private int catId;
     private Serializable catLive;
     private Serializable catName1;
     private Serializable catName2;
     private Serializable catName3;
     private Serializable catName4;
     private Serializable catName5;
     private Serializable catDesc1;
     private Serializable catDesc2;
     private Serializable catDesc3;
     private Serializable catDesc4;
     private Serializable catDesc5;
     private Serializable catProductDisplayType;
     private Serializable catSubCatDisplayType;
     private Double catOrderByValue;
     private Serializable catOrderProductsBy;
     private Integer catCustomerGroupId;

    public Categories() {
    }

	
    public Categories(int catId) {
        this.catId = catId;
    }
    public Categories(int catId, Serializable catLive, Serializable catName1, Serializable catName2, Serializable catName3, Serializable catName4, Serializable catName5, Serializable catDesc1, Serializable catDesc2, Serializable catDesc3, Serializable catDesc4, Serializable catDesc5, Serializable catProductDisplayType, Serializable catSubCatDisplayType, Double catOrderByValue, Serializable catOrderProductsBy, Integer catCustomerGroupId) {
       this.catId = catId;
       this.catLive = catLive;
       this.catName1 = catName1;
       this.catName2 = catName2;
       this.catName3 = catName3;
       this.catName4 = catName4;
       this.catName5 = catName5;
       this.catDesc1 = catDesc1;
       this.catDesc2 = catDesc2;
       this.catDesc3 = catDesc3;
       this.catDesc4 = catDesc4;
       this.catDesc5 = catDesc5;
       this.catProductDisplayType = catProductDisplayType;
       this.catSubCatDisplayType = catSubCatDisplayType;
       this.catOrderByValue = catOrderByValue;
       this.catOrderProductsBy = catOrderProductsBy;
       this.catCustomerGroupId = catCustomerGroupId;
    }
   
    public int getCatId() {
        return this.catId;
    }
    
    public void setCatId(int catId) {
        this.catId = catId;
    }
    public Serializable getCatLive() {
        return this.catLive;
    }
    
    public void setCatLive(Serializable catLive) {
        this.catLive = catLive;
    }
    public Serializable getCatName1() {
        return this.catName1;
    }
    
    public void setCatName1(Serializable catName1) {
        this.catName1 = catName1;
    }
    public Serializable getCatName2() {
        return this.catName2;
    }
    
    public void setCatName2(Serializable catName2) {
        this.catName2 = catName2;
    }
    public Serializable getCatName3() {
        return this.catName3;
    }
    
    public void setCatName3(Serializable catName3) {
        this.catName3 = catName3;
    }
    public Serializable getCatName4() {
        return this.catName4;
    }
    
    public void setCatName4(Serializable catName4) {
        this.catName4 = catName4;
    }
    public Serializable getCatName5() {
        return this.catName5;
    }
    
    public void setCatName5(Serializable catName5) {
        this.catName5 = catName5;
    }
    public Serializable getCatDesc1() {
        return this.catDesc1;
    }
    
    public void setCatDesc1(Serializable catDesc1) {
        this.catDesc1 = catDesc1;
    }
    public Serializable getCatDesc2() {
        return this.catDesc2;
    }
    
    public void setCatDesc2(Serializable catDesc2) {
        this.catDesc2 = catDesc2;
    }
    public Serializable getCatDesc3() {
        return this.catDesc3;
    }
    
    public void setCatDesc3(Serializable catDesc3) {
        this.catDesc3 = catDesc3;
    }
    public Serializable getCatDesc4() {
        return this.catDesc4;
    }
    
    public void setCatDesc4(Serializable catDesc4) {
        this.catDesc4 = catDesc4;
    }
    public Serializable getCatDesc5() {
        return this.catDesc5;
    }
    
    public void setCatDesc5(Serializable catDesc5) {
        this.catDesc5 = catDesc5;
    }
    public Serializable getCatProductDisplayType() {
        return this.catProductDisplayType;
    }
    
    public void setCatProductDisplayType(Serializable catProductDisplayType) {
        this.catProductDisplayType = catProductDisplayType;
    }
    public Serializable getCatSubCatDisplayType() {
        return this.catSubCatDisplayType;
    }
    
    public void setCatSubCatDisplayType(Serializable catSubCatDisplayType) {
        this.catSubCatDisplayType = catSubCatDisplayType;
    }
    public Double getCatOrderByValue() {
        return this.catOrderByValue;
    }
    
    public void setCatOrderByValue(Double catOrderByValue) {
        this.catOrderByValue = catOrderByValue;
    }
    public Serializable getCatOrderProductsBy() {
        return this.catOrderProductsBy;
    }
    
    public void setCatOrderProductsBy(Serializable catOrderProductsBy) {
        this.catOrderProductsBy = catOrderProductsBy;
    }
    public Integer getCatCustomerGroupId() {
        return this.catCustomerGroupId;
    }
    
    public void setCatCustomerGroupId(Integer catCustomerGroupId) {
        this.catCustomerGroupId = catCustomerGroupId;
    }




}


