package model.utils;
// Generated Mar 19, 2017 8:47:25 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories  implements java.io.Serializable {


     private int categoryId;
     private Serializable categoryName;
     private Serializable description;
     private byte[] picture;
     private Set productses = new HashSet(0);

    public Categories() {
    }

	
    public Categories(int categoryId, Serializable categoryName) {
        this.categoryId = categoryId;
        this.categoryName = categoryName;
    }
    public Categories(int categoryId, Serializable categoryName, Serializable description, byte[] picture, Set productses) {
       this.categoryId = categoryId;
       this.categoryName = categoryName;
       this.description = description;
       this.picture = picture;
       this.productses = productses;
    }
   
    public int getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }
    public Serializable getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(Serializable categoryName) {
        this.categoryName = categoryName;
    }
    public Serializable getDescription() {
        return this.description;
    }
    
    public void setDescription(Serializable description) {
        this.description = description;
    }
    public byte[] getPicture() {
        return this.picture;
    }
    
    public void setPicture(byte[] picture) {
        this.picture = picture;
    }
    public Set getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set productses) {
        this.productses = productses;
    }




}


