package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * ConfigCategories generated by hbm2java
 */
public class ConfigCategories  implements java.io.Serializable {


     private int cfgcId;
     private Integer cfgcParentId;
     private Serializable cfgcCategory;
     private Integer cfgcOrderByValue;

    public ConfigCategories() {
    }

	
    public ConfigCategories(int cfgcId) {
        this.cfgcId = cfgcId;
    }
    public ConfigCategories(int cfgcId, Integer cfgcParentId, Serializable cfgcCategory, Integer cfgcOrderByValue) {
       this.cfgcId = cfgcId;
       this.cfgcParentId = cfgcParentId;
       this.cfgcCategory = cfgcCategory;
       this.cfgcOrderByValue = cfgcOrderByValue;
    }
   
    public int getCfgcId() {
        return this.cfgcId;
    }
    
    public void setCfgcId(int cfgcId) {
        this.cfgcId = cfgcId;
    }
    public Integer getCfgcParentId() {
        return this.cfgcParentId;
    }
    
    public void setCfgcParentId(Integer cfgcParentId) {
        this.cfgcParentId = cfgcParentId;
    }
    public Serializable getCfgcCategory() {
        return this.cfgcCategory;
    }
    
    public void setCfgcCategory(Serializable cfgcCategory) {
        this.cfgcCategory = cfgcCategory;
    }
    public Integer getCfgcOrderByValue() {
        return this.cfgcOrderByValue;
    }
    
    public void setCfgcOrderByValue(Integer cfgcOrderByValue) {
        this.cfgcOrderByValue = cfgcOrderByValue;
    }




}


