package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Config generated by hbm2java
 */
public class Config  implements java.io.Serializable {


     private Serializable cfgName;
     private Serializable cfgValue;
     private Serializable cfgDataType;
     private Serializable cfgDisplayType;
     private Serializable cfgDisplayInfo;
     private Serializable cfgDescription;
     private Float cfgVersionAdded;
     private Serializable cfgDefaultValue;
     private Integer cfgConfigCategoryId;

    public Config() {
    }

	
    public Config(Serializable cfgName) {
        this.cfgName = cfgName;
    }
    public Config(Serializable cfgName, Serializable cfgValue, Serializable cfgDataType, Serializable cfgDisplayType, Serializable cfgDisplayInfo, Serializable cfgDescription, Float cfgVersionAdded, Serializable cfgDefaultValue, Integer cfgConfigCategoryId) {
       this.cfgName = cfgName;
       this.cfgValue = cfgValue;
       this.cfgDataType = cfgDataType;
       this.cfgDisplayType = cfgDisplayType;
       this.cfgDisplayInfo = cfgDisplayInfo;
       this.cfgDescription = cfgDescription;
       this.cfgVersionAdded = cfgVersionAdded;
       this.cfgDefaultValue = cfgDefaultValue;
       this.cfgConfigCategoryId = cfgConfigCategoryId;
    }
   
    public Serializable getCfgName() {
        return this.cfgName;
    }
    
    public void setCfgName(Serializable cfgName) {
        this.cfgName = cfgName;
    }
    public Serializable getCfgValue() {
        return this.cfgValue;
    }
    
    public void setCfgValue(Serializable cfgValue) {
        this.cfgValue = cfgValue;
    }
    public Serializable getCfgDataType() {
        return this.cfgDataType;
    }
    
    public void setCfgDataType(Serializable cfgDataType) {
        this.cfgDataType = cfgDataType;
    }
    public Serializable getCfgDisplayType() {
        return this.cfgDisplayType;
    }
    
    public void setCfgDisplayType(Serializable cfgDisplayType) {
        this.cfgDisplayType = cfgDisplayType;
    }
    public Serializable getCfgDisplayInfo() {
        return this.cfgDisplayInfo;
    }
    
    public void setCfgDisplayInfo(Serializable cfgDisplayInfo) {
        this.cfgDisplayInfo = cfgDisplayInfo;
    }
    public Serializable getCfgDescription() {
        return this.cfgDescription;
    }
    
    public void setCfgDescription(Serializable cfgDescription) {
        this.cfgDescription = cfgDescription;
    }
    public Float getCfgVersionAdded() {
        return this.cfgVersionAdded;
    }
    
    public void setCfgVersionAdded(Float cfgVersionAdded) {
        this.cfgVersionAdded = cfgVersionAdded;
    }
    public Serializable getCfgDefaultValue() {
        return this.cfgDefaultValue;
    }
    
    public void setCfgDefaultValue(Serializable cfgDefaultValue) {
        this.cfgDefaultValue = cfgDefaultValue;
    }
    public Integer getCfgConfigCategoryId() {
        return this.cfgConfigCategoryId;
    }
    
    public void setCfgConfigCategoryId(Integer cfgConfigCategoryId) {
        this.cfgConfigCategoryId = cfgConfigCategoryId;
    }




}


