package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * Coupons generated by hbm2java
 */
public class Coupons  implements java.io.Serializable {


     private int cpId;
     private Serializable cpCouponCode;
     private Serializable cpReusable;
     private Serializable cpUsed;
     private Date cpCreatedTime;
     private Date cpStartDate;
     private Date cpEndDate;
     private Float cpDiscountValue;
     private Serializable cpDiscountType;
     private Serializable cpEnabled;

    public Coupons() {
    }

	
    public Coupons(int cpId) {
        this.cpId = cpId;
    }
    public Coupons(int cpId, Serializable cpCouponCode, Serializable cpReusable, Serializable cpUsed, Date cpCreatedTime, Date cpStartDate, Date cpEndDate, Float cpDiscountValue, Serializable cpDiscountType, Serializable cpEnabled) {
       this.cpId = cpId;
       this.cpCouponCode = cpCouponCode;
       this.cpReusable = cpReusable;
       this.cpUsed = cpUsed;
       this.cpCreatedTime = cpCreatedTime;
       this.cpStartDate = cpStartDate;
       this.cpEndDate = cpEndDate;
       this.cpDiscountValue = cpDiscountValue;
       this.cpDiscountType = cpDiscountType;
       this.cpEnabled = cpEnabled;
    }
   
    public int getCpId() {
        return this.cpId;
    }
    
    public void setCpId(int cpId) {
        this.cpId = cpId;
    }
    public Serializable getCpCouponCode() {
        return this.cpCouponCode;
    }
    
    public void setCpCouponCode(Serializable cpCouponCode) {
        this.cpCouponCode = cpCouponCode;
    }
    public Serializable getCpReusable() {
        return this.cpReusable;
    }
    
    public void setCpReusable(Serializable cpReusable) {
        this.cpReusable = cpReusable;
    }
    public Serializable getCpUsed() {
        return this.cpUsed;
    }
    
    public void setCpUsed(Serializable cpUsed) {
        this.cpUsed = cpUsed;
    }
    public Date getCpCreatedTime() {
        return this.cpCreatedTime;
    }
    
    public void setCpCreatedTime(Date cpCreatedTime) {
        this.cpCreatedTime = cpCreatedTime;
    }
    public Date getCpStartDate() {
        return this.cpStartDate;
    }
    
    public void setCpStartDate(Date cpStartDate) {
        this.cpStartDate = cpStartDate;
    }
    public Date getCpEndDate() {
        return this.cpEndDate;
    }
    
    public void setCpEndDate(Date cpEndDate) {
        this.cpEndDate = cpEndDate;
    }
    public Float getCpDiscountValue() {
        return this.cpDiscountValue;
    }
    
    public void setCpDiscountValue(Float cpDiscountValue) {
        this.cpDiscountValue = cpDiscountValue;
    }
    public Serializable getCpDiscountType() {
        return this.cpDiscountType;
    }
    
    public void setCpDiscountType(Serializable cpDiscountType) {
        this.cpDiscountType = cpDiscountType;
    }
    public Serializable getCpEnabled() {
        return this.cpEnabled;
    }
    
    public void setCpEnabled(Serializable cpEnabled) {
        this.cpEnabled = cpEnabled;
    }




}


