package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * CreditCards generated by hbm2java
 */
public class CreditCards  implements java.io.Serializable {


     private int crId;
     private Serializable crName;
     private Serializable crAccepted;

    public CreditCards() {
    }

	
    public CreditCards(int crId) {
        this.crId = crId;
    }
    public CreditCards(int crId, Serializable crName, Serializable crAccepted) {
       this.crId = crId;
       this.crName = crName;
       this.crAccepted = crAccepted;
    }
   
    public int getCrId() {
        return this.crId;
    }
    
    public void setCrId(int crId) {
        this.crId = crId;
    }
    public Serializable getCrName() {
        return this.crName;
    }
    
    public void setCrName(Serializable crName) {
        this.crName = crName;
    }
    public Serializable getCrAccepted() {
        return this.crAccepted;
    }
    
    public void setCrAccepted(Serializable crAccepted) {
        this.crAccepted = crAccepted;
    }




}


