package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Currencies generated by hbm2java
 */
public class Currencies  implements java.io.Serializable {


     private int curId;
     private Serializable curSymbol;
     private Serializable curIsocode;
     private Serializable curName1;
     private Serializable curName2;
     private Serializable curName3;
     private Serializable curName4;
     private Serializable curName5;
     private Float curExchangeRate;
     private Serializable curHasDecimals;
     private Serializable curLive;
     private Serializable curFormat;
     private Serializable curIsoFormat;
     private Serializable curDecimalPoint;

    public Currencies() {
    }

	
    public Currencies(int curId) {
        this.curId = curId;
    }
    public Currencies(int curId, Serializable curSymbol, Serializable curIsocode, Serializable curName1, Serializable curName2, Serializable curName3, Serializable curName4, Serializable curName5, Float curExchangeRate, Serializable curHasDecimals, Serializable curLive, Serializable curFormat, Serializable curIsoFormat, Serializable curDecimalPoint) {
       this.curId = curId;
       this.curSymbol = curSymbol;
       this.curIsocode = curIsocode;
       this.curName1 = curName1;
       this.curName2 = curName2;
       this.curName3 = curName3;
       this.curName4 = curName4;
       this.curName5 = curName5;
       this.curExchangeRate = curExchangeRate;
       this.curHasDecimals = curHasDecimals;
       this.curLive = curLive;
       this.curFormat = curFormat;
       this.curIsoFormat = curIsoFormat;
       this.curDecimalPoint = curDecimalPoint;
    }
   
    public int getCurId() {
        return this.curId;
    }
    
    public void setCurId(int curId) {
        this.curId = curId;
    }
    public Serializable getCurSymbol() {
        return this.curSymbol;
    }
    
    public void setCurSymbol(Serializable curSymbol) {
        this.curSymbol = curSymbol;
    }
    public Serializable getCurIsocode() {
        return this.curIsocode;
    }
    
    public void setCurIsocode(Serializable curIsocode) {
        this.curIsocode = curIsocode;
    }
    public Serializable getCurName1() {
        return this.curName1;
    }
    
    public void setCurName1(Serializable curName1) {
        this.curName1 = curName1;
    }
    public Serializable getCurName2() {
        return this.curName2;
    }
    
    public void setCurName2(Serializable curName2) {
        this.curName2 = curName2;
    }
    public Serializable getCurName3() {
        return this.curName3;
    }
    
    public void setCurName3(Serializable curName3) {
        this.curName3 = curName3;
    }
    public Serializable getCurName4() {
        return this.curName4;
    }
    
    public void setCurName4(Serializable curName4) {
        this.curName4 = curName4;
    }
    public Serializable getCurName5() {
        return this.curName5;
    }
    
    public void setCurName5(Serializable curName5) {
        this.curName5 = curName5;
    }
    public Float getCurExchangeRate() {
        return this.curExchangeRate;
    }
    
    public void setCurExchangeRate(Float curExchangeRate) {
        this.curExchangeRate = curExchangeRate;
    }
    public Serializable getCurHasDecimals() {
        return this.curHasDecimals;
    }
    
    public void setCurHasDecimals(Serializable curHasDecimals) {
        this.curHasDecimals = curHasDecimals;
    }
    public Serializable getCurLive() {
        return this.curLive;
    }
    
    public void setCurLive(Serializable curLive) {
        this.curLive = curLive;
    }
    public Serializable getCurFormat() {
        return this.curFormat;
    }
    
    public void setCurFormat(Serializable curFormat) {
        this.curFormat = curFormat;
    }
    public Serializable getCurIsoFormat() {
        return this.curIsoFormat;
    }
    
    public void setCurIsoFormat(Serializable curIsoFormat) {
        this.curIsoFormat = curIsoFormat;
    }
    public Serializable getCurDecimalPoint() {
        return this.curDecimalPoint;
    }
    
    public void setCurDecimalPoint(Serializable curDecimalPoint) {
        this.curDecimalPoint = curDecimalPoint;
    }




}


