package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1



/**
 * CustomerGroupPrices generated by hbm2java
 */
public class CustomerGroupPrices  implements java.io.Serializable {


     private int cgpId;
     private Integer cgpCustomerGroupId;
     private Integer cgpVersionId;
     private Double cgpPrice;

    public CustomerGroupPrices() {
    }

	
    public CustomerGroupPrices(int cgpId) {
        this.cgpId = cgpId;
    }
    public CustomerGroupPrices(int cgpId, Integer cgpCustomerGroupId, Integer cgpVersionId, Double cgpPrice) {
       this.cgpId = cgpId;
       this.cgpCustomerGroupId = cgpCustomerGroupId;
       this.cgpVersionId = cgpVersionId;
       this.cgpPrice = cgpPrice;
    }
   
    public int getCgpId() {
        return this.cgpId;
    }
    
    public void setCgpId(int cgpId) {
        this.cgpId = cgpId;
    }
    public Integer getCgpCustomerGroupId() {
        return this.cgpCustomerGroupId;
    }
    
    public void setCgpCustomerGroupId(Integer cgpCustomerGroupId) {
        this.cgpCustomerGroupId = cgpCustomerGroupId;
    }
    public Integer getCgpVersionId() {
        return this.cgpVersionId;
    }
    
    public void setCgpVersionId(Integer cgpVersionId) {
        this.cgpVersionId = cgpVersionId;
    }
    public Double getCgpPrice() {
        return this.cgpPrice;
    }
    
    public void setCgpPrice(Double cgpPrice) {
        this.cgpPrice = cgpPrice;
    }




}


