package model.utils;
// Generated Mar 19, 2017 8:47:25 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * CustomerDemographics generated by hbm2java
 */
public class CustomerDemographics  implements java.io.Serializable {


     private Serializable customerTypeId;
     private Serializable customerDesc;
     private Set customerses = new HashSet(0);

    public CustomerDemographics() {
    }

	
    public CustomerDemographics(Serializable customerTypeId) {
        this.customerTypeId = customerTypeId;
    }
    public CustomerDemographics(Serializable customerTypeId, Serializable customerDesc, Set customerses) {
       this.customerTypeId = customerTypeId;
       this.customerDesc = customerDesc;
       this.customerses = customerses;
    }
   
    public Serializable getCustomerTypeId() {
        return this.customerTypeId;
    }
    
    public void setCustomerTypeId(Serializable customerTypeId) {
        this.customerTypeId = customerTypeId;
    }
    public Serializable getCustomerDesc() {
        return this.customerDesc;
    }
    
    public void setCustomerDesc(Serializable customerDesc) {
        this.customerDesc = customerDesc;
    }
    public Set getCustomerses() {
        return this.customerses;
    }
    
    public void setCustomerses(Set customerses) {
        this.customerses = customerses;
    }




}


