package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * CustomerGroups generated by hbm2java
 */
public class CustomerGroups  implements java.io.Serializable {


     private int cgId;
     private Serializable cgName1;
     private Serializable cgName2;
     private Serializable cgName3;
     private Serializable cgName4;
     private Serializable cgName5;
     private Integer cgDiscount;
     private Serializable cgLive;

    public CustomerGroups() {
    }

	
    public CustomerGroups(int cgId) {
        this.cgId = cgId;
    }
    public CustomerGroups(int cgId, Serializable cgName1, Serializable cgName2, Serializable cgName3, Serializable cgName4, Serializable cgName5, Integer cgDiscount, Serializable cgLive) {
       this.cgId = cgId;
       this.cgName1 = cgName1;
       this.cgName2 = cgName2;
       this.cgName3 = cgName3;
       this.cgName4 = cgName4;
       this.cgName5 = cgName5;
       this.cgDiscount = cgDiscount;
       this.cgLive = cgLive;
    }
   
    public int getCgId() {
        return this.cgId;
    }
    
    public void setCgId(int cgId) {
        this.cgId = cgId;
    }
    public Serializable getCgName1() {
        return this.cgName1;
    }
    
    public void setCgName1(Serializable cgName1) {
        this.cgName1 = cgName1;
    }
    public Serializable getCgName2() {
        return this.cgName2;
    }
    
    public void setCgName2(Serializable cgName2) {
        this.cgName2 = cgName2;
    }
    public Serializable getCgName3() {
        return this.cgName3;
    }
    
    public void setCgName3(Serializable cgName3) {
        this.cgName3 = cgName3;
    }
    public Serializable getCgName4() {
        return this.cgName4;
    }
    
    public void setCgName4(Serializable cgName4) {
        this.cgName4 = cgName4;
    }
    public Serializable getCgName5() {
        return this.cgName5;
    }
    
    public void setCgName5(Serializable cgName5) {
        this.cgName5 = cgName5;
    }
    public Integer getCgDiscount() {
        return this.cgDiscount;
    }
    
    public void setCgDiscount(Integer cgDiscount) {
        this.cgDiscount = cgDiscount;
    }
    public Serializable getCgLive() {
        return this.cgLive;
    }
    
    public void setCgLive(Serializable cgLive) {
        this.cgLive = cgLive;
    }




}


