package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1



/**
 * Destination generated by hbm2java
 */
public class Destination  implements java.io.Serializable {


     private DestinationId id;

    public Destination() {
    }

    public Destination(DestinationId id) {
       this.id = id;
    }
   
    public DestinationId getId() {
        return this.id;
    }
    
    public void setId(DestinationId id) {
        this.id = id;
    }




}


