package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * DestinationId generated by hbm2java
 */
public class DestinationId  implements java.io.Serializable {


     private int DId;
     private Serializable DDestination1;
     private Serializable DDestination2;
     private Serializable DDestination3;
     private Serializable DDestination4;
     private Serializable DDestination5;
     private Integer DShippingZoneId;
     private Double DTax;
     private Serializable DIsocode;
     private Serializable DLive;

    public DestinationId() {
    }

	
    public DestinationId(int DId) {
        this.DId = DId;
    }
    public DestinationId(int DId, Serializable DDestination1, Serializable DDestination2, Serializable DDestination3, Serializable DDestination4, Serializable DDestination5, Integer DShippingZoneId, Double DTax, Serializable DIsocode, Serializable DLive) {
       this.DId = DId;
       this.DDestination1 = DDestination1;
       this.DDestination2 = DDestination2;
       this.DDestination3 = DDestination3;
       this.DDestination4 = DDestination4;
       this.DDestination5 = DDestination5;
       this.DShippingZoneId = DShippingZoneId;
       this.DTax = DTax;
       this.DIsocode = DIsocode;
       this.DLive = DLive;
    }
   
    public int getDId() {
        return this.DId;
    }
    
    public void setDId(int DId) {
        this.DId = DId;
    }
    public Serializable getDDestination1() {
        return this.DDestination1;
    }
    
    public void setDDestination1(Serializable DDestination1) {
        this.DDestination1 = DDestination1;
    }
    public Serializable getDDestination2() {
        return this.DDestination2;
    }
    
    public void setDDestination2(Serializable DDestination2) {
        this.DDestination2 = DDestination2;
    }
    public Serializable getDDestination3() {
        return this.DDestination3;
    }
    
    public void setDDestination3(Serializable DDestination3) {
        this.DDestination3 = DDestination3;
    }
    public Serializable getDDestination4() {
        return this.DDestination4;
    }
    
    public void setDDestination4(Serializable DDestination4) {
        this.DDestination4 = DDestination4;
    }
    public Serializable getDDestination5() {
        return this.DDestination5;
    }
    
    public void setDDestination5(Serializable DDestination5) {
        this.DDestination5 = DDestination5;
    }
    public Integer getDShippingZoneId() {
        return this.DShippingZoneId;
    }
    
    public void setDShippingZoneId(Integer DShippingZoneId) {
        this.DShippingZoneId = DShippingZoneId;
    }
    public Double getDTax() {
        return this.DTax;
    }
    
    public void setDTax(Double DTax) {
        this.DTax = DTax;
    }
    public Serializable getDIsocode() {
        return this.DIsocode;
    }
    
    public void setDIsocode(Serializable DIsocode) {
        this.DIsocode = DIsocode;
    }
    public Serializable getDLive() {
        return this.DLive;
    }
    
    public void setDLive(Serializable DLive) {
        this.DLive = DLive;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DestinationId) ) return false;
		 DestinationId castOther = ( DestinationId ) other; 
         
		 return (this.getDId()==castOther.getDId())
 && ( (this.getDDestination1()==castOther.getDDestination1()) || ( this.getDDestination1()!=null && castOther.getDDestination1()!=null && this.getDDestination1().equals(castOther.getDDestination1()) ) )
 && ( (this.getDDestination2()==castOther.getDDestination2()) || ( this.getDDestination2()!=null && castOther.getDDestination2()!=null && this.getDDestination2().equals(castOther.getDDestination2()) ) )
 && ( (this.getDDestination3()==castOther.getDDestination3()) || ( this.getDDestination3()!=null && castOther.getDDestination3()!=null && this.getDDestination3().equals(castOther.getDDestination3()) ) )
 && ( (this.getDDestination4()==castOther.getDDestination4()) || ( this.getDDestination4()!=null && castOther.getDDestination4()!=null && this.getDDestination4().equals(castOther.getDDestination4()) ) )
 && ( (this.getDDestination5()==castOther.getDDestination5()) || ( this.getDDestination5()!=null && castOther.getDDestination5()!=null && this.getDDestination5().equals(castOther.getDDestination5()) ) )
 && ( (this.getDShippingZoneId()==castOther.getDShippingZoneId()) || ( this.getDShippingZoneId()!=null && castOther.getDShippingZoneId()!=null && this.getDShippingZoneId().equals(castOther.getDShippingZoneId()) ) )
 && ( (this.getDTax()==castOther.getDTax()) || ( this.getDTax()!=null && castOther.getDTax()!=null && this.getDTax().equals(castOther.getDTax()) ) )
 && ( (this.getDIsocode()==castOther.getDIsocode()) || ( this.getDIsocode()!=null && castOther.getDIsocode()!=null && this.getDIsocode().equals(castOther.getDIsocode()) ) )
 && ( (this.getDLive()==castOther.getDLive()) || ( this.getDLive()!=null && castOther.getDLive()!=null && this.getDLive().equals(castOther.getDLive()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getDId();
         result = 37 * result + ( getDDestination1() == null ? 0 : this.getDDestination1().hashCode() );
         result = 37 * result + ( getDDestination2() == null ? 0 : this.getDDestination2().hashCode() );
         result = 37 * result + ( getDDestination3() == null ? 0 : this.getDDestination3().hashCode() );
         result = 37 * result + ( getDDestination4() == null ? 0 : this.getDDestination4().hashCode() );
         result = 37 * result + ( getDDestination5() == null ? 0 : this.getDDestination5().hashCode() );
         result = 37 * result + ( getDShippingZoneId() == null ? 0 : this.getDShippingZoneId().hashCode() );
         result = 37 * result + ( getDTax() == null ? 0 : this.getDTax().hashCode() );
         result = 37 * result + ( getDIsocode() == null ? 0 : this.getDIsocode().hashCode() );
         result = 37 * result + ( getDLive() == null ? 0 : this.getDLive().hashCode() );
         return result;
   }   


}


