package model.utils;
// Generated Mar 19, 2017 8:47:25 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employees generated by hbm2java
 */
public class Employees  implements java.io.Serializable {


     private int employeeId;
     private Employees employees;
     private Serializable lastName;
     private Serializable firstName;
     private Serializable title;
     private Serializable titleOfCourtesy;
     private Date birthDate;
     private Date hireDate;
     private Serializable address;
     private Serializable city;
     private Serializable region;
     private Serializable postalCode;
     private Serializable country;
     private Serializable homePhone;
     private Serializable extension;
     private byte[] photo;
     private Serializable notes;
     private Serializable photoPath;
     private Set territorieses = new HashSet(0);
     private Set orderses = new HashSet(0);
     private Set loginses = new HashSet(0);
     private Set employeeses = new HashSet(0);

    public Employees() {
    }

	
    public Employees(int employeeId, Serializable lastName, Serializable firstName) {
        this.employeeId = employeeId;
        this.lastName = lastName;
        this.firstName = firstName;
    }
    public Employees(int employeeId, Employees employees, Serializable lastName, Serializable firstName, Serializable title, Serializable titleOfCourtesy, Date birthDate, Date hireDate, Serializable address, Serializable city, Serializable region, Serializable postalCode, Serializable country, Serializable homePhone, Serializable extension, byte[] photo, Serializable notes, Serializable photoPath, Set territorieses, Set orderses, Set loginses, Set employeeses) {
       this.employeeId = employeeId;
       this.employees = employees;
       this.lastName = lastName;
       this.firstName = firstName;
       this.title = title;
       this.titleOfCourtesy = titleOfCourtesy;
       this.birthDate = birthDate;
       this.hireDate = hireDate;
       this.address = address;
       this.city = city;
       this.region = region;
       this.postalCode = postalCode;
       this.country = country;
       this.homePhone = homePhone;
       this.extension = extension;
       this.photo = photo;
       this.notes = notes;
       this.photoPath = photoPath;
       this.territorieses = territorieses;
       this.orderses = orderses;
       this.loginses = loginses;
       this.employeeses = employeeses;
    }
   
    public int getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public Serializable getLastName() {
        return this.lastName;
    }
    
    public void setLastName(Serializable lastName) {
        this.lastName = lastName;
    }
    public Serializable getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(Serializable firstName) {
        this.firstName = firstName;
    }
    public Serializable getTitle() {
        return this.title;
    }
    
    public void setTitle(Serializable title) {
        this.title = title;
    }
    public Serializable getTitleOfCourtesy() {
        return this.titleOfCourtesy;
    }
    
    public void setTitleOfCourtesy(Serializable titleOfCourtesy) {
        this.titleOfCourtesy = titleOfCourtesy;
    }
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
    public Date getHireDate() {
        return this.hireDate;
    }
    
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }
    public Serializable getAddress() {
        return this.address;
    }
    
    public void setAddress(Serializable address) {
        this.address = address;
    }
    public Serializable getCity() {
        return this.city;
    }
    
    public void setCity(Serializable city) {
        this.city = city;
    }
    public Serializable getRegion() {
        return this.region;
    }
    
    public void setRegion(Serializable region) {
        this.region = region;
    }
    public Serializable getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(Serializable postalCode) {
        this.postalCode = postalCode;
    }
    public Serializable getCountry() {
        return this.country;
    }
    
    public void setCountry(Serializable country) {
        this.country = country;
    }
    public Serializable getHomePhone() {
        return this.homePhone;
    }
    
    public void setHomePhone(Serializable homePhone) {
        this.homePhone = homePhone;
    }
    public Serializable getExtension() {
        return this.extension;
    }
    
    public void setExtension(Serializable extension) {
        this.extension = extension;
    }
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
    public Serializable getNotes() {
        return this.notes;
    }
    
    public void setNotes(Serializable notes) {
        this.notes = notes;
    }
    public Serializable getPhotoPath() {
        return this.photoPath;
    }
    
    public void setPhotoPath(Serializable photoPath) {
        this.photoPath = photoPath;
    }
    public Set getTerritorieses() {
        return this.territorieses;
    }
    
    public void setTerritorieses(Set territorieses) {
        this.territorieses = territorieses;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }
    public Set getLoginses() {
        return this.loginses;
    }
    
    public void setLoginses(Set loginses) {
        this.loginses = loginses;
    }
    public Set getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set employeeses) {
        this.employeeses = employeeses;
    }




}


