package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * InvoiceRows generated by hbm2java
 */
public class InvoiceRows  implements java.io.Serializable {


     private int irId;
     private Integer irOrderNumberId;
     private Serializable irVersionCode;
     private Serializable irVersionName;
     private Integer irQuantity;
     private Double irPricePerItem;
     private Double irTaxPerItem;
     private Serializable irOptionsText;

    public InvoiceRows() {
    }

	
    public InvoiceRows(int irId) {
        this.irId = irId;
    }
    public InvoiceRows(int irId, Integer irOrderNumberId, Serializable irVersionCode, Serializable irVersionName, Integer irQuantity, Double irPricePerItem, Double irTaxPerItem, Serializable irOptionsText) {
       this.irId = irId;
       this.irOrderNumberId = irOrderNumberId;
       this.irVersionCode = irVersionCode;
       this.irVersionName = irVersionName;
       this.irQuantity = irQuantity;
       this.irPricePerItem = irPricePerItem;
       this.irTaxPerItem = irTaxPerItem;
       this.irOptionsText = irOptionsText;
    }
   
    public int getIrId() {
        return this.irId;
    }
    
    public void setIrId(int irId) {
        this.irId = irId;
    }
    public Integer getIrOrderNumberId() {
        return this.irOrderNumberId;
    }
    
    public void setIrOrderNumberId(Integer irOrderNumberId) {
        this.irOrderNumberId = irOrderNumberId;
    }
    public Serializable getIrVersionCode() {
        return this.irVersionCode;
    }
    
    public void setIrVersionCode(Serializable irVersionCode) {
        this.irVersionCode = irVersionCode;
    }
    public Serializable getIrVersionName() {
        return this.irVersionName;
    }
    
    public void setIrVersionName(Serializable irVersionName) {
        this.irVersionName = irVersionName;
    }
    public Integer getIrQuantity() {
        return this.irQuantity;
    }
    
    public void setIrQuantity(Integer irQuantity) {
        this.irQuantity = irQuantity;
    }
    public Double getIrPricePerItem() {
        return this.irPricePerItem;
    }
    
    public void setIrPricePerItem(Double irPricePerItem) {
        this.irPricePerItem = irPricePerItem;
    }
    public Double getIrTaxPerItem() {
        return this.irTaxPerItem;
    }
    
    public void setIrTaxPerItem(Double irTaxPerItem) {
        this.irTaxPerItem = irTaxPerItem;
    }
    public Serializable getIrOptionsText() {
        return this.irOptionsText;
    }
    
    public void setIrOptionsText(Serializable irOptionsText) {
        this.irOptionsText = irOptionsText;
    }




}


