package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * LanguagesId generated by hbm2java
 */
public class LanguagesId  implements java.io.Serializable {


     private Integer langId;
     private Serializable langBackName;
     private Serializable langFrontName;
     private Serializable langSkinLocation;
     private Serializable langLiveFront;
     private Serializable langLiveBack;
     private Serializable langEmailFrom;
     private Serializable langEmailTo;
     private Serializable langEmailToContact;
     private Serializable langDateFormat;
     private Serializable langDateAndTimeFormat;

    public LanguagesId() {
    }

    public LanguagesId(Integer langId, Serializable langBackName, Serializable langFrontName, Serializable langSkinLocation, Serializable langLiveFront, Serializable langLiveBack, Serializable langEmailFrom, Serializable langEmailTo, Serializable langEmailToContact, Serializable langDateFormat, Serializable langDateAndTimeFormat) {
       this.langId = langId;
       this.langBackName = langBackName;
       this.langFrontName = langFrontName;
       this.langSkinLocation = langSkinLocation;
       this.langLiveFront = langLiveFront;
       this.langLiveBack = langLiveBack;
       this.langEmailFrom = langEmailFrom;
       this.langEmailTo = langEmailTo;
       this.langEmailToContact = langEmailToContact;
       this.langDateFormat = langDateFormat;
       this.langDateAndTimeFormat = langDateAndTimeFormat;
    }
   
    public Integer getLangId() {
        return this.langId;
    }
    
    public void setLangId(Integer langId) {
        this.langId = langId;
    }
    public Serializable getLangBackName() {
        return this.langBackName;
    }
    
    public void setLangBackName(Serializable langBackName) {
        this.langBackName = langBackName;
    }
    public Serializable getLangFrontName() {
        return this.langFrontName;
    }
    
    public void setLangFrontName(Serializable langFrontName) {
        this.langFrontName = langFrontName;
    }
    public Serializable getLangSkinLocation() {
        return this.langSkinLocation;
    }
    
    public void setLangSkinLocation(Serializable langSkinLocation) {
        this.langSkinLocation = langSkinLocation;
    }
    public Serializable getLangLiveFront() {
        return this.langLiveFront;
    }
    
    public void setLangLiveFront(Serializable langLiveFront) {
        this.langLiveFront = langLiveFront;
    }
    public Serializable getLangLiveBack() {
        return this.langLiveBack;
    }
    
    public void setLangLiveBack(Serializable langLiveBack) {
        this.langLiveBack = langLiveBack;
    }
    public Serializable getLangEmailFrom() {
        return this.langEmailFrom;
    }
    
    public void setLangEmailFrom(Serializable langEmailFrom) {
        this.langEmailFrom = langEmailFrom;
    }
    public Serializable getLangEmailTo() {
        return this.langEmailTo;
    }
    
    public void setLangEmailTo(Serializable langEmailTo) {
        this.langEmailTo = langEmailTo;
    }
    public Serializable getLangEmailToContact() {
        return this.langEmailToContact;
    }
    
    public void setLangEmailToContact(Serializable langEmailToContact) {
        this.langEmailToContact = langEmailToContact;
    }
    public Serializable getLangDateFormat() {
        return this.langDateFormat;
    }
    
    public void setLangDateFormat(Serializable langDateFormat) {
        this.langDateFormat = langDateFormat;
    }
    public Serializable getLangDateAndTimeFormat() {
        return this.langDateAndTimeFormat;
    }
    
    public void setLangDateAndTimeFormat(Serializable langDateAndTimeFormat) {
        this.langDateAndTimeFormat = langDateAndTimeFormat;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LanguagesId) ) return false;
		 LanguagesId castOther = ( LanguagesId ) other; 
         
		 return ( (this.getLangId()==castOther.getLangId()) || ( this.getLangId()!=null && castOther.getLangId()!=null && this.getLangId().equals(castOther.getLangId()) ) )
 && ( (this.getLangBackName()==castOther.getLangBackName()) || ( this.getLangBackName()!=null && castOther.getLangBackName()!=null && this.getLangBackName().equals(castOther.getLangBackName()) ) )
 && ( (this.getLangFrontName()==castOther.getLangFrontName()) || ( this.getLangFrontName()!=null && castOther.getLangFrontName()!=null && this.getLangFrontName().equals(castOther.getLangFrontName()) ) )
 && ( (this.getLangSkinLocation()==castOther.getLangSkinLocation()) || ( this.getLangSkinLocation()!=null && castOther.getLangSkinLocation()!=null && this.getLangSkinLocation().equals(castOther.getLangSkinLocation()) ) )
 && ( (this.getLangLiveFront()==castOther.getLangLiveFront()) || ( this.getLangLiveFront()!=null && castOther.getLangLiveFront()!=null && this.getLangLiveFront().equals(castOther.getLangLiveFront()) ) )
 && ( (this.getLangLiveBack()==castOther.getLangLiveBack()) || ( this.getLangLiveBack()!=null && castOther.getLangLiveBack()!=null && this.getLangLiveBack().equals(castOther.getLangLiveBack()) ) )
 && ( (this.getLangEmailFrom()==castOther.getLangEmailFrom()) || ( this.getLangEmailFrom()!=null && castOther.getLangEmailFrom()!=null && this.getLangEmailFrom().equals(castOther.getLangEmailFrom()) ) )
 && ( (this.getLangEmailTo()==castOther.getLangEmailTo()) || ( this.getLangEmailTo()!=null && castOther.getLangEmailTo()!=null && this.getLangEmailTo().equals(castOther.getLangEmailTo()) ) )
 && ( (this.getLangEmailToContact()==castOther.getLangEmailToContact()) || ( this.getLangEmailToContact()!=null && castOther.getLangEmailToContact()!=null && this.getLangEmailToContact().equals(castOther.getLangEmailToContact()) ) )
 && ( (this.getLangDateFormat()==castOther.getLangDateFormat()) || ( this.getLangDateFormat()!=null && castOther.getLangDateFormat()!=null && this.getLangDateFormat().equals(castOther.getLangDateFormat()) ) )
 && ( (this.getLangDateAndTimeFormat()==castOther.getLangDateAndTimeFormat()) || ( this.getLangDateAndTimeFormat()!=null && castOther.getLangDateAndTimeFormat()!=null && this.getLangDateAndTimeFormat().equals(castOther.getLangDateAndTimeFormat()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLangId() == null ? 0 : this.getLangId().hashCode() );
         result = 37 * result + ( getLangBackName() == null ? 0 : this.getLangBackName().hashCode() );
         result = 37 * result + ( getLangFrontName() == null ? 0 : this.getLangFrontName().hashCode() );
         result = 37 * result + ( getLangSkinLocation() == null ? 0 : this.getLangSkinLocation().hashCode() );
         result = 37 * result + ( getLangLiveFront() == null ? 0 : this.getLangLiveFront().hashCode() );
         result = 37 * result + ( getLangLiveBack() == null ? 0 : this.getLangLiveBack().hashCode() );
         result = 37 * result + ( getLangEmailFrom() == null ? 0 : this.getLangEmailFrom().hashCode() );
         result = 37 * result + ( getLangEmailTo() == null ? 0 : this.getLangEmailTo().hashCode() );
         result = 37 * result + ( getLangEmailToContact() == null ? 0 : this.getLangEmailToContact().hashCode() );
         result = 37 * result + ( getLangDateFormat() == null ? 0 : this.getLangDateFormat().hashCode() );
         result = 37 * result + ( getLangDateAndTimeFormat() == null ? 0 : this.getLangDateAndTimeFormat().hashCode() );
         return result;
   }   


}


