package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1



/**
 * Languages generated by hbm2java
 */
public class Languages  implements java.io.Serializable {


     private LanguagesId id;

    public Languages() {
    }

    public Languages(LanguagesId id) {
       this.id = id;
    }
   
    public LanguagesId getId() {
        return this.id;
    }
    
    public void setId(LanguagesId id) {
        this.id = id;
    }




}


