package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Logins generated by hbm2java
 */
public class Logins  implements java.io.Serializable {


     private int loginId;
     private Serializable loginUsername;
     private Serializable loginPassword;
     private Serializable loginLive;
     private Serializable loginOrders;
     private Serializable loginProducts;
     private Serializable loginConfig;
     private Serializable loginProtected;
     private Serializable loginLanguageId;
     private Serializable loginRandomHash;

    public Logins() {
    }

	
    public Logins(int loginId) {
        this.loginId = loginId;
    }
    public Logins(int loginId, Serializable loginUsername, Serializable loginPassword, Serializable loginLive, Serializable loginOrders, Serializable loginProducts, Serializable loginConfig, Serializable loginProtected, Serializable loginLanguageId, Serializable loginRandomHash) {
       this.loginId = loginId;
       this.loginUsername = loginUsername;
       this.loginPassword = loginPassword;
       this.loginLive = loginLive;
       this.loginOrders = loginOrders;
       this.loginProducts = loginProducts;
       this.loginConfig = loginConfig;
       this.loginProtected = loginProtected;
       this.loginLanguageId = loginLanguageId;
       this.loginRandomHash = loginRandomHash;
    }
   
    public int getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(int loginId) {
        this.loginId = loginId;
    }
    public Serializable getLoginUsername() {
        return this.loginUsername;
    }
    
    public void setLoginUsername(Serializable loginUsername) {
        this.loginUsername = loginUsername;
    }
    public Serializable getLoginPassword() {
        return this.loginPassword;
    }
    
    public void setLoginPassword(Serializable loginPassword) {
        this.loginPassword = loginPassword;
    }
    public Serializable getLoginLive() {
        return this.loginLive;
    }
    
    public void setLoginLive(Serializable loginLive) {
        this.loginLive = loginLive;
    }
    public Serializable getLoginOrders() {
        return this.loginOrders;
    }
    
    public void setLoginOrders(Serializable loginOrders) {
        this.loginOrders = loginOrders;
    }
    public Serializable getLoginProducts() {
        return this.loginProducts;
    }
    
    public void setLoginProducts(Serializable loginProducts) {
        this.loginProducts = loginProducts;
    }
    public Serializable getLoginConfig() {
        return this.loginConfig;
    }
    
    public void setLoginConfig(Serializable loginConfig) {
        this.loginConfig = loginConfig;
    }
    public Serializable getLoginProtected() {
        return this.loginProtected;
    }
    
    public void setLoginProtected(Serializable loginProtected) {
        this.loginProtected = loginProtected;
    }
    public Serializable getLoginLanguageId() {
        return this.loginLanguageId;
    }
    
    public void setLoginLanguageId(Serializable loginLanguageId) {
        this.loginLanguageId = loginLanguageId;
    }
    public Serializable getLoginRandomHash() {
        return this.loginRandomHash;
    }
    
    public void setLoginRandomHash(Serializable loginRandomHash) {
        this.loginRandomHash = loginRandomHash;
    }




}


