package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


/**
 * Logins generated by hbm2java
 */
public class Logins   {


     private int loginId;
     private String loginUsername;
     private String loginPassword;
     private String loginLive;
     private String loginOrders;
     private String loginProducts;
     private String loginConfig;
     private String loginProtected;
     private String loginLanguageId;
     private String loginRandomHash;

    public Logins() {
    }

	
    public Logins(int loginId) {
        this.loginId = loginId;
    }
    public Logins(int loginId, String loginUsername, String loginPassword, String loginLive, String loginOrders, String loginProducts, String loginConfig, String loginProtected, String loginLanguageId, String loginRandomHash) {
       this.loginId = loginId;
       this.loginUsername = loginUsername;
       this.loginPassword = loginPassword;
       this.loginLive = loginLive;
       this.loginOrders = loginOrders;
       this.loginProducts = loginProducts;
       this.loginConfig = loginConfig;
       this.loginProtected = loginProtected;
       this.loginLanguageId = loginLanguageId;
       this.loginRandomHash = loginRandomHash;
    }
   
    public int getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(int loginId) {
        this.loginId = loginId;
    }
    public String getLoginUsername() {
        return this.loginUsername;
    }
    
    public void setLoginUsername(String loginUsername) {
        this.loginUsername = loginUsername;
    }
    public String getLoginPassword() {
        return this.loginPassword;
    }
    
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword;
    }
    public String getLoginLive() {
        return this.loginLive;
    }
    
    public void setLoginLive(String loginLive) {
        this.loginLive = loginLive;
    }
    public String getLoginOrders() {
        return this.loginOrders;
    }
    
    public void setLoginOrders(String loginOrders) {
        this.loginOrders = loginOrders;
    }
    public String getLoginProducts() {
        return this.loginProducts;
    }
    
    public void setLoginProducts(String loginProducts) {
        this.loginProducts = loginProducts;
    }
    public String getLoginConfig() {
        return this.loginConfig;
    }
    
    public void setLoginConfig(String loginConfig) {
        this.loginConfig = loginConfig;
    }
    public String getLoginProtected() {
        return this.loginProtected;
    }
    
    public void setLoginProtected(String loginProtected) {
        this.loginProtected = loginProtected;
    }
    public String getLoginLanguageId() {
        return this.loginLanguageId;
    }
    
    public void setLoginLanguageId(String loginLanguageId) {
        this.loginLanguageId = loginLanguageId;
    }
    public String getLoginRandomHash() {
        return this.loginRandomHash;
    }
    
    public void setLoginRandomHash(String loginRandomHash) {
        this.loginRandomHash = loginRandomHash;
    }




}


