package model.utils;
// Generated Mar 19, 2017 8:47:25 PM by Hibernate Tools 4.3.1



/**
 * Logins generated by hbm2java
 */
public class Logins  implements java.io.Serializable {


     private long loginId;
     private Employees employees;
     private String username;
     private String passwordHash;

    public Logins() {
    }

	
    public Logins(long loginId) {
        this.loginId = loginId;
    }
    public Logins(long loginId, Employees employees, String username, String passwordHash) {
       this.loginId = loginId;
       this.employees = employees;
       this.username = username;
       this.passwordHash = passwordHash;
    }
   
    public long getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(long loginId) {
        this.loginId = loginId;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPasswordHash() {
        return this.passwordHash;
    }
    
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }




}


