package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * News generated by hbm2java
 */
public class News  implements java.io.Serializable {


     private int NId;
     private Serializable NHeadline;
     private Serializable NContent;
     private Integer NLanguageId;

    public News() {
    }

	
    public News(int NId) {
        this.NId = NId;
    }
    public News(int NId, Serializable NHeadline, Serializable NContent, Integer NLanguageId) {
       this.NId = NId;
       this.NHeadline = NHeadline;
       this.NContent = NContent;
       this.NLanguageId = NLanguageId;
    }
   
    public int getNId() {
        return this.NId;
    }
    
    public void setNId(int NId) {
        this.NId = NId;
    }
    public Serializable getNHeadline() {
        return this.NHeadline;
    }
    
    public void setNHeadline(Serializable NHeadline) {
        this.NHeadline = NHeadline;
    }
    public Serializable getNContent() {
        return this.NContent;
    }
    
    public void setNContent(Serializable NContent) {
        this.NContent = NContent;
    }
    public Integer getNLanguageId() {
        return this.NLanguageId;
    }
    
    public void setNLanguageId(Integer NLanguageId) {
        this.NLanguageId = NLanguageId;
    }




}


