package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Options generated by hbm2java
 */
public class Options  implements java.io.Serializable {


     private int optId;
     private Integer optOptionGroupId;
     private Serializable optName1;
     private Serializable optName2;
     private Serializable optName3;
     private Serializable optName4;
     private Serializable optName5;
     private Serializable optCheckBoxValue;
     private Double optDefPriceChange;
     private Double optDefWeightChange;
     private Float optDefOrderByValue;

    public Options() {
    }

	
    public Options(int optId) {
        this.optId = optId;
    }
    public Options(int optId, Integer optOptionGroupId, Serializable optName1, Serializable optName2, Serializable optName3, Serializable optName4, Serializable optName5, Serializable optCheckBoxValue, Double optDefPriceChange, Double optDefWeightChange, Float optDefOrderByValue) {
       this.optId = optId;
       this.optOptionGroupId = optOptionGroupId;
       this.optName1 = optName1;
       this.optName2 = optName2;
       this.optName3 = optName3;
       this.optName4 = optName4;
       this.optName5 = optName5;
       this.optCheckBoxValue = optCheckBoxValue;
       this.optDefPriceChange = optDefPriceChange;
       this.optDefWeightChange = optDefWeightChange;
       this.optDefOrderByValue = optDefOrderByValue;
    }
   
    public int getOptId() {
        return this.optId;
    }
    
    public void setOptId(int optId) {
        this.optId = optId;
    }
    public Integer getOptOptionGroupId() {
        return this.optOptionGroupId;
    }
    
    public void setOptOptionGroupId(Integer optOptionGroupId) {
        this.optOptionGroupId = optOptionGroupId;
    }
    public Serializable getOptName1() {
        return this.optName1;
    }
    
    public void setOptName1(Serializable optName1) {
        this.optName1 = optName1;
    }
    public Serializable getOptName2() {
        return this.optName2;
    }
    
    public void setOptName2(Serializable optName2) {
        this.optName2 = optName2;
    }
    public Serializable getOptName3() {
        return this.optName3;
    }
    
    public void setOptName3(Serializable optName3) {
        this.optName3 = optName3;
    }
    public Serializable getOptName4() {
        return this.optName4;
    }
    
    public void setOptName4(Serializable optName4) {
        this.optName4 = optName4;
    }
    public Serializable getOptName5() {
        return this.optName5;
    }
    
    public void setOptName5(Serializable optName5) {
        this.optName5 = optName5;
    }
    public Serializable getOptCheckBoxValue() {
        return this.optCheckBoxValue;
    }
    
    public void setOptCheckBoxValue(Serializable optCheckBoxValue) {
        this.optCheckBoxValue = optCheckBoxValue;
    }
    public Double getOptDefPriceChange() {
        return this.optDefPriceChange;
    }
    
    public void setOptDefPriceChange(Double optDefPriceChange) {
        this.optDefPriceChange = optDefPriceChange;
    }
    public Double getOptDefWeightChange() {
        return this.optDefWeightChange;
    }
    
    public void setOptDefWeightChange(Double optDefWeightChange) {
        this.optDefWeightChange = optDefWeightChange;
    }
    public Float getOptDefOrderByValue() {
        return this.optDefOrderByValue;
    }
    
    public void setOptDefOrderByValue(Float optDefOrderByValue) {
        this.optDefOrderByValue = optDefOrderByValue;
    }




}


