package model.utils;
// Generated Mar 19, 2017 8:47:25 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * OrderDetails generated by hbm2java
 */
public class OrderDetails  implements java.io.Serializable {


     private OrderDetailsId id;
     private Orders orders;
     private Products products;
     private BigDecimal unitPrice;
     private short quantity;
     private float discount;

    public OrderDetails() {
    }

    public OrderDetails(OrderDetailsId id, Orders orders, Products products, BigDecimal unitPrice, short quantity, float discount) {
       this.id = id;
       this.orders = orders;
       this.products = products;
       this.unitPrice = unitPrice;
       this.quantity = quantity;
       this.discount = discount;
    }
   
    public OrderDetailsId getId() {
        return this.id;
    }
    
    public void setId(OrderDetailsId id) {
        this.id = id;
    }
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }
    public short getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(short quantity) {
        this.quantity = quantity;
    }
    public float getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(float discount) {
        this.discount = discount;
    }




}


