package model.utils;
// Generated Mar 19, 2017 8:47:25 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private int orderId;
     private Customers customers;
     private Employees employees;
     private Shippers shippers;
     private Date orderDate;
     private Date requiredDate;
     private Date shippedDate;
     private BigDecimal freight;
     private Serializable shipName;
     private Serializable shipAddress;
     private Serializable shipCity;
     private Serializable shipRegion;
     private Serializable shipPostalCode;
     private Serializable shipCountry;
     private Set orderDetailses = new HashSet(0);

    public Orders() {
    }

	
    public Orders(int orderId) {
        this.orderId = orderId;
    }
    public Orders(int orderId, Customers customers, Employees employees, Shippers shippers, Date orderDate, Date requiredDate, Date shippedDate, BigDecimal freight, Serializable shipName, Serializable shipAddress, Serializable shipCity, Serializable shipRegion, Serializable shipPostalCode, Serializable shipCountry, Set orderDetailses) {
       this.orderId = orderId;
       this.customers = customers;
       this.employees = employees;
       this.shippers = shippers;
       this.orderDate = orderDate;
       this.requiredDate = requiredDate;
       this.shippedDate = shippedDate;
       this.freight = freight;
       this.shipName = shipName;
       this.shipAddress = shipAddress;
       this.shipCity = shipCity;
       this.shipRegion = shipRegion;
       this.shipPostalCode = shipPostalCode;
       this.shipCountry = shipCountry;
       this.orderDetailses = orderDetailses;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public Shippers getShippers() {
        return this.shippers;
    }
    
    public void setShippers(Shippers shippers) {
        this.shippers = shippers;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public Date getRequiredDate() {
        return this.requiredDate;
    }
    
    public void setRequiredDate(Date requiredDate) {
        this.requiredDate = requiredDate;
    }
    public Date getShippedDate() {
        return this.shippedDate;
    }
    
    public void setShippedDate(Date shippedDate) {
        this.shippedDate = shippedDate;
    }
    public BigDecimal getFreight() {
        return this.freight;
    }
    
    public void setFreight(BigDecimal freight) {
        this.freight = freight;
    }
    public Serializable getShipName() {
        return this.shipName;
    }
    
    public void setShipName(Serializable shipName) {
        this.shipName = shipName;
    }
    public Serializable getShipAddress() {
        return this.shipAddress;
    }
    
    public void setShipAddress(Serializable shipAddress) {
        this.shipAddress = shipAddress;
    }
    public Serializable getShipCity() {
        return this.shipCity;
    }
    
    public void setShipCity(Serializable shipCity) {
        this.shipCity = shipCity;
    }
    public Serializable getShipRegion() {
        return this.shipRegion;
    }
    
    public void setShipRegion(Serializable shipRegion) {
        this.shipRegion = shipRegion;
    }
    public Serializable getShipPostalCode() {
        return this.shipPostalCode;
    }
    
    public void setShipPostalCode(Serializable shipPostalCode) {
        this.shipPostalCode = shipPostalCode;
    }
    public Serializable getShipCountry() {
        return this.shipCountry;
    }
    
    public void setShipCountry(Serializable shipCountry) {
        this.shipCountry = shipCountry;
    }
    public Set getOrderDetailses() {
        return this.orderDetailses;
    }
    
    public void setOrderDetailses(Set orderDetailses) {
        this.orderDetailses = orderDetailses;
    }




}


