package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Pages generated by hbm2java
 */
public class Pages  implements java.io.Serializable {


     private Serializable pageId;
     private Serializable pageTitle1;
     private Serializable pageText1;
     private Serializable pageMetaDescription1;
     private Serializable pageMetaKeywords1;
     private Serializable pageTitle2;
     private Serializable pageText2;
     private Serializable pageMetaDescription2;
     private Serializable pageMetaKeywords2;
     private Serializable pageTitle3;
     private Serializable pageText3;
     private Serializable pageMetaDescription3;
     private Serializable pageMetaKeywords3;
     private Serializable pageTitle4;
     private Serializable pageText4;
     private Serializable pageMetaDescription4;
     private Serializable pageMetaKeywords4;
     private Serializable pageTitle5;
     private Serializable pageText5;
     private Serializable pageMetaDescription5;
     private Serializable pageMetaKeywords5;
     private Serializable pageLive;

    public Pages() {
    }

	
    public Pages(Serializable pageId) {
        this.pageId = pageId;
    }
    public Pages(Serializable pageId, Serializable pageTitle1, Serializable pageText1, Serializable pageMetaDescription1, Serializable pageMetaKeywords1, Serializable pageTitle2, Serializable pageText2, Serializable pageMetaDescription2, Serializable pageMetaKeywords2, Serializable pageTitle3, Serializable pageText3, Serializable pageMetaDescription3, Serializable pageMetaKeywords3, Serializable pageTitle4, Serializable pageText4, Serializable pageMetaDescription4, Serializable pageMetaKeywords4, Serializable pageTitle5, Serializable pageText5, Serializable pageMetaDescription5, Serializable pageMetaKeywords5, Serializable pageLive) {
       this.pageId = pageId;
       this.pageTitle1 = pageTitle1;
       this.pageText1 = pageText1;
       this.pageMetaDescription1 = pageMetaDescription1;
       this.pageMetaKeywords1 = pageMetaKeywords1;
       this.pageTitle2 = pageTitle2;
       this.pageText2 = pageText2;
       this.pageMetaDescription2 = pageMetaDescription2;
       this.pageMetaKeywords2 = pageMetaKeywords2;
       this.pageTitle3 = pageTitle3;
       this.pageText3 = pageText3;
       this.pageMetaDescription3 = pageMetaDescription3;
       this.pageMetaKeywords3 = pageMetaKeywords3;
       this.pageTitle4 = pageTitle4;
       this.pageText4 = pageText4;
       this.pageMetaDescription4 = pageMetaDescription4;
       this.pageMetaKeywords4 = pageMetaKeywords4;
       this.pageTitle5 = pageTitle5;
       this.pageText5 = pageText5;
       this.pageMetaDescription5 = pageMetaDescription5;
       this.pageMetaKeywords5 = pageMetaKeywords5;
       this.pageLive = pageLive;
    }
   
    public Serializable getPageId() {
        return this.pageId;
    }
    
    public void setPageId(Serializable pageId) {
        this.pageId = pageId;
    }
    public Serializable getPageTitle1() {
        return this.pageTitle1;
    }
    
    public void setPageTitle1(Serializable pageTitle1) {
        this.pageTitle1 = pageTitle1;
    }
    public Serializable getPageText1() {
        return this.pageText1;
    }
    
    public void setPageText1(Serializable pageText1) {
        this.pageText1 = pageText1;
    }
    public Serializable getPageMetaDescription1() {
        return this.pageMetaDescription1;
    }
    
    public void setPageMetaDescription1(Serializable pageMetaDescription1) {
        this.pageMetaDescription1 = pageMetaDescription1;
    }
    public Serializable getPageMetaKeywords1() {
        return this.pageMetaKeywords1;
    }
    
    public void setPageMetaKeywords1(Serializable pageMetaKeywords1) {
        this.pageMetaKeywords1 = pageMetaKeywords1;
    }
    public Serializable getPageTitle2() {
        return this.pageTitle2;
    }
    
    public void setPageTitle2(Serializable pageTitle2) {
        this.pageTitle2 = pageTitle2;
    }
    public Serializable getPageText2() {
        return this.pageText2;
    }
    
    public void setPageText2(Serializable pageText2) {
        this.pageText2 = pageText2;
    }
    public Serializable getPageMetaDescription2() {
        return this.pageMetaDescription2;
    }
    
    public void setPageMetaDescription2(Serializable pageMetaDescription2) {
        this.pageMetaDescription2 = pageMetaDescription2;
    }
    public Serializable getPageMetaKeywords2() {
        return this.pageMetaKeywords2;
    }
    
    public void setPageMetaKeywords2(Serializable pageMetaKeywords2) {
        this.pageMetaKeywords2 = pageMetaKeywords2;
    }
    public Serializable getPageTitle3() {
        return this.pageTitle3;
    }
    
    public void setPageTitle3(Serializable pageTitle3) {
        this.pageTitle3 = pageTitle3;
    }
    public Serializable getPageText3() {
        return this.pageText3;
    }
    
    public void setPageText3(Serializable pageText3) {
        this.pageText3 = pageText3;
    }
    public Serializable getPageMetaDescription3() {
        return this.pageMetaDescription3;
    }
    
    public void setPageMetaDescription3(Serializable pageMetaDescription3) {
        this.pageMetaDescription3 = pageMetaDescription3;
    }
    public Serializable getPageMetaKeywords3() {
        return this.pageMetaKeywords3;
    }
    
    public void setPageMetaKeywords3(Serializable pageMetaKeywords3) {
        this.pageMetaKeywords3 = pageMetaKeywords3;
    }
    public Serializable getPageTitle4() {
        return this.pageTitle4;
    }
    
    public void setPageTitle4(Serializable pageTitle4) {
        this.pageTitle4 = pageTitle4;
    }
    public Serializable getPageText4() {
        return this.pageText4;
    }
    
    public void setPageText4(Serializable pageText4) {
        this.pageText4 = pageText4;
    }
    public Serializable getPageMetaDescription4() {
        return this.pageMetaDescription4;
    }
    
    public void setPageMetaDescription4(Serializable pageMetaDescription4) {
        this.pageMetaDescription4 = pageMetaDescription4;
    }
    public Serializable getPageMetaKeywords4() {
        return this.pageMetaKeywords4;
    }
    
    public void setPageMetaKeywords4(Serializable pageMetaKeywords4) {
        this.pageMetaKeywords4 = pageMetaKeywords4;
    }
    public Serializable getPageTitle5() {
        return this.pageTitle5;
    }
    
    public void setPageTitle5(Serializable pageTitle5) {
        this.pageTitle5 = pageTitle5;
    }
    public Serializable getPageText5() {
        return this.pageText5;
    }
    
    public void setPageText5(Serializable pageText5) {
        this.pageText5 = pageText5;
    }
    public Serializable getPageMetaDescription5() {
        return this.pageMetaDescription5;
    }
    
    public void setPageMetaDescription5(Serializable pageMetaDescription5) {
        this.pageMetaDescription5 = pageMetaDescription5;
    }
    public Serializable getPageMetaKeywords5() {
        return this.pageMetaKeywords5;
    }
    
    public void setPageMetaKeywords5(Serializable pageMetaKeywords5) {
        this.pageMetaKeywords5 = pageMetaKeywords5;
    }
    public Serializable getPageLive() {
        return this.pageLive;
    }
    
    public void setPageLive(Serializable pageLive) {
        this.pageLive = pageLive;
    }




}


