package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1



/**
 * ProductCategoryLinkId generated by hbm2java
 */
public class ProductCategoryLinkId  implements java.io.Serializable {


     private Integer pcatProductId;
     private Integer pcatCategoryId;

    public ProductCategoryLinkId() {
    }

    public ProductCategoryLinkId(Integer pcatProductId, Integer pcatCategoryId) {
       this.pcatProductId = pcatProductId;
       this.pcatCategoryId = pcatCategoryId;
    }
   
    public Integer getPcatProductId() {
        return this.pcatProductId;
    }
    
    public void setPcatProductId(Integer pcatProductId) {
        this.pcatProductId = pcatProductId;
    }
    public Integer getPcatCategoryId() {
        return this.pcatCategoryId;
    }
    
    public void setPcatCategoryId(Integer pcatCategoryId) {
        this.pcatCategoryId = pcatCategoryId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductCategoryLinkId) ) return false;
		 ProductCategoryLinkId castOther = ( ProductCategoryLinkId ) other; 
         
		 return ( (this.getPcatProductId()==castOther.getPcatProductId()) || ( this.getPcatProductId()!=null && castOther.getPcatProductId()!=null && this.getPcatProductId().equals(castOther.getPcatProductId()) ) )
 && ( (this.getPcatCategoryId()==castOther.getPcatCategoryId()) || ( this.getPcatCategoryId()!=null && castOther.getPcatCategoryId()!=null && this.getPcatCategoryId().equals(castOther.getPcatCategoryId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPcatProductId() == null ? 0 : this.getPcatProductId().hashCode() );
         result = 37 * result + ( getPcatCategoryId() == null ? 0 : this.getPcatCategoryId().hashCode() );
         return result;
   }   


}


