package model.utils;
// Generated Mar 19, 2017 8:47:25 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.SQLQuery;
import org.hibernate.Session;
import static uitils.HibernateUtil.getSessionFactory;
import uitils.shaSecure;

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

    private int productNo;
    private int productId;
    private Categories categories;
    private Suppliers suppliers;
    private String productName;
    private String quantityPerUnit;
    private BigDecimal unitPrice;
    private Short unitsInStock;
    private Short unitsOnOrder;
    private Short reorderLevel;
    private boolean discontinued;
    private Set orderDetailses = new HashSet(0);

    public Products() {
    }

    public Products(int productNo, int productId, String productName, boolean discontinued) {
        this.productNo = productNo;
        this.productId = productId;
        this.productName = productName;
        this.discontinued = discontinued;
    }

    public Products(int productNo, int productId, Categories categories, Suppliers suppliers, String productName, String quantityPerUnit, BigDecimal unitPrice, Short unitsInStock, Short unitsOnOrder, Short reorderLevel, boolean discontinued, Set orderDetailses) {
        this.productNo = productNo;
        this.productId = productId;
        this.categories = categories;
        this.suppliers = suppliers;
        this.productName = productName;
        this.quantityPerUnit = quantityPerUnit;
        this.unitPrice = unitPrice;
        this.unitsInStock = unitsInStock;
        this.unitsOnOrder = unitsOnOrder;
        this.reorderLevel = reorderLevel;
        this.discontinued = discontinued;
        this.orderDetailses = orderDetailses;
    }

    public int getProductNo() {
        return this.productNo;
    }

    public void setProductNo(int productNo) {
        this.productNo = productNo;
    }

    public int getProductId() {
        return this.productId;
    }

    public void setProductId(int productId) {
        this.productId = productId;
    }

    public Categories getCategories() {
        return this.categories;
    }

    public void setCategories(Categories categories) {
        this.categories = categories;
    }

    public Suppliers getSuppliers() {
        return this.suppliers;
    }

    public void setSuppliers(Suppliers suppliers) {
        this.suppliers = suppliers;
    }

    public String getProductName() {
        return this.productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getQuantityPerUnit() {
        return this.quantityPerUnit;
    }

    public void setQuantityPerUnit(String quantityPerUnit) {
        this.quantityPerUnit = quantityPerUnit;
    }

    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }

    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    public Short getUnitsInStock() {
        return this.unitsInStock;
    }

    public void setUnitsInStock(Short unitsInStock) {
        this.unitsInStock = unitsInStock;
    }

    public Short getUnitsOnOrder() {
        return this.unitsOnOrder;
    }

    public void setUnitsOnOrder(Short unitsOnOrder) {
        this.unitsOnOrder = unitsOnOrder;
    }

    public Short getReorderLevel() {
        return this.reorderLevel;
    }

    public void setReorderLevel(Short reorderLevel) {
        this.reorderLevel = reorderLevel;
    }

    public boolean isDiscontinued() {
        return this.discontinued;
    }

    public void setDiscontinued(boolean discontinued) {
        this.discontinued = discontinued;
    }

    public Set getOrderDetailses() {
        return this.orderDetailses;
    }

    public void setOrderDetailses(Set orderDetailses) {
        this.orderDetailses = orderDetailses;
    }

    public List<Products> getAllProduct() {
        Session session = getSessionFactory().openSession();
        SQLQuery query = session.createSQLQuery("select * from Products");
        query.addEntity(Products.class);
        List<Products> list = query.list();
        return list;
    }

    public List<Products> getAllProductListInfor() {
        try {
            Session session = getSessionFactory().openSession();
            SQLQuery query = session.createSQLQuery("select ROW_NUMBER() OVER(ORDER BY ProductID ASC) AS ProductNo,* from Products A , Categories B where A.CategoryID=B.CategoryID ");
            query.addEntity(Products.class);
            // query.addJoin("");
            List<Products> rows = query.list();

            return rows;

        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
        return null;
    }
}
