package model.utils;
// Generated Mar 19, 2017 8:47:25 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private int productId;
     private Categories categories;
     private Suppliers suppliers;
     private Serializable productName;
     private Serializable quantityPerUnit;
     private BigDecimal unitPrice;
     private Short unitsInStock;
     private Short unitsOnOrder;
     private Short reorderLevel;
     private boolean discontinued;
     private Set orderDetailses = new HashSet(0);

    public Products() {
    }

	
    public Products(int productId, Serializable productName, boolean discontinued) {
        this.productId = productId;
        this.productName = productName;
        this.discontinued = discontinued;
    }
    public Products(int productId, Categories categories, Suppliers suppliers, Serializable productName, Serializable quantityPerUnit, BigDecimal unitPrice, Short unitsInStock, Short unitsOnOrder, Short reorderLevel, boolean discontinued, Set orderDetailses) {
       this.productId = productId;
       this.categories = categories;
       this.suppliers = suppliers;
       this.productName = productName;
       this.quantityPerUnit = quantityPerUnit;
       this.unitPrice = unitPrice;
       this.unitsInStock = unitsInStock;
       this.unitsOnOrder = unitsOnOrder;
       this.reorderLevel = reorderLevel;
       this.discontinued = discontinued;
       this.orderDetailses = orderDetailses;
    }
   
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }
    public Suppliers getSuppliers() {
        return this.suppliers;
    }
    
    public void setSuppliers(Suppliers suppliers) {
        this.suppliers = suppliers;
    }
    public Serializable getProductName() {
        return this.productName;
    }
    
    public void setProductName(Serializable productName) {
        this.productName = productName;
    }
    public Serializable getQuantityPerUnit() {
        return this.quantityPerUnit;
    }
    
    public void setQuantityPerUnit(Serializable quantityPerUnit) {
        this.quantityPerUnit = quantityPerUnit;
    }
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Short getUnitsInStock() {
        return this.unitsInStock;
    }
    
    public void setUnitsInStock(Short unitsInStock) {
        this.unitsInStock = unitsInStock;
    }
    public Short getUnitsOnOrder() {
        return this.unitsOnOrder;
    }
    
    public void setUnitsOnOrder(Short unitsOnOrder) {
        this.unitsOnOrder = unitsOnOrder;
    }
    public Short getReorderLevel() {
        return this.reorderLevel;
    }
    
    public void setReorderLevel(Short reorderLevel) {
        this.reorderLevel = reorderLevel;
    }
    public boolean isDiscontinued() {
        return this.discontinued;
    }
    
    public void setDiscontinued(boolean discontinued) {
        this.discontinued = discontinued;
    }
    public Set getOrderDetailses() {
        return this.orderDetailses;
    }
    
    public void setOrderDetailses(Set orderDetailses) {
        this.orderDetailses = orderDetailses;
    }




}


