package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1



/**
 * ProductOptionGroupLink generated by hbm2java
 */
public class ProductOptionGroupLink  implements java.io.Serializable {


     private ProductOptionGroupLinkId id;

    public ProductOptionGroupLink() {
    }

    public ProductOptionGroupLink(ProductOptionGroupLinkId id) {
       this.id = id;
    }
   
    public ProductOptionGroupLinkId getId() {
        return this.id;
    }
    
    public void setId(ProductOptionGroupLinkId id) {
        this.id = id;
    }




}


