package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * ProductStats generated by hbm2java
 */
public class ProductStats  implements java.io.Serializable {


     private int psId;
     private Integer psProductId;
     private Date psDate;
     private Serializable psIp;

    public ProductStats() {
    }

	
    public ProductStats(int psId) {
        this.psId = psId;
    }
    public ProductStats(int psId, Integer psProductId, Date psDate, Serializable psIp) {
       this.psId = psId;
       this.psProductId = psProductId;
       this.psDate = psDate;
       this.psIp = psIp;
    }
   
    public int getPsId() {
        return this.psId;
    }
    
    public void setPsId(int psId) {
        this.psId = psId;
    }
    public Integer getPsProductId() {
        return this.psProductId;
    }
    
    public void setPsProductId(Integer psProductId) {
        this.psProductId = psProductId;
    }
    public Date getPsDate() {
        return this.psDate;
    }
    
    public void setPsDate(Date psDate) {
        this.psDate = psDate;
    }
    public Serializable getPsIp() {
        return this.psIp;
    }
    
    public void setPsIp(Serializable psIp) {
        this.psIp = psIp;
    }




}


