package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * ProductOptionLinkId generated by hbm2java
 */
public class ProductOptionLinkId  implements java.io.Serializable {


     private Integer POptOptionId;
     private Integer POptProductId;
     private Integer POptOrderByValue;
     private Double POptPriceChange;
     private Double POptWeightChange;
     private Serializable POptSelected;

    public ProductOptionLinkId() {
    }

    public ProductOptionLinkId(Integer POptOptionId, Integer POptProductId, Integer POptOrderByValue, Double POptPriceChange, Double POptWeightChange, Serializable POptSelected) {
       this.POptOptionId = POptOptionId;
       this.POptProductId = POptProductId;
       this.POptOrderByValue = POptOrderByValue;
       this.POptPriceChange = POptPriceChange;
       this.POptWeightChange = POptWeightChange;
       this.POptSelected = POptSelected;
    }
   
    public Integer getPOptOptionId() {
        return this.POptOptionId;
    }
    
    public void setPOptOptionId(Integer POptOptionId) {
        this.POptOptionId = POptOptionId;
    }
    public Integer getPOptProductId() {
        return this.POptProductId;
    }
    
    public void setPOptProductId(Integer POptProductId) {
        this.POptProductId = POptProductId;
    }
    public Integer getPOptOrderByValue() {
        return this.POptOrderByValue;
    }
    
    public void setPOptOrderByValue(Integer POptOrderByValue) {
        this.POptOrderByValue = POptOrderByValue;
    }
    public Double getPOptPriceChange() {
        return this.POptPriceChange;
    }
    
    public void setPOptPriceChange(Double POptPriceChange) {
        this.POptPriceChange = POptPriceChange;
    }
    public Double getPOptWeightChange() {
        return this.POptWeightChange;
    }
    
    public void setPOptWeightChange(Double POptWeightChange) {
        this.POptWeightChange = POptWeightChange;
    }
    public Serializable getPOptSelected() {
        return this.POptSelected;
    }
    
    public void setPOptSelected(Serializable POptSelected) {
        this.POptSelected = POptSelected;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductOptionLinkId) ) return false;
		 ProductOptionLinkId castOther = ( ProductOptionLinkId ) other; 
         
		 return ( (this.getPOptOptionId()==castOther.getPOptOptionId()) || ( this.getPOptOptionId()!=null && castOther.getPOptOptionId()!=null && this.getPOptOptionId().equals(castOther.getPOptOptionId()) ) )
 && ( (this.getPOptProductId()==castOther.getPOptProductId()) || ( this.getPOptProductId()!=null && castOther.getPOptProductId()!=null && this.getPOptProductId().equals(castOther.getPOptProductId()) ) )
 && ( (this.getPOptOrderByValue()==castOther.getPOptOrderByValue()) || ( this.getPOptOrderByValue()!=null && castOther.getPOptOrderByValue()!=null && this.getPOptOrderByValue().equals(castOther.getPOptOrderByValue()) ) )
 && ( (this.getPOptPriceChange()==castOther.getPOptPriceChange()) || ( this.getPOptPriceChange()!=null && castOther.getPOptPriceChange()!=null && this.getPOptPriceChange().equals(castOther.getPOptPriceChange()) ) )
 && ( (this.getPOptWeightChange()==castOther.getPOptWeightChange()) || ( this.getPOptWeightChange()!=null && castOther.getPOptWeightChange()!=null && this.getPOptWeightChange().equals(castOther.getPOptWeightChange()) ) )
 && ( (this.getPOptSelected()==castOther.getPOptSelected()) || ( this.getPOptSelected()!=null && castOther.getPOptSelected()!=null && this.getPOptSelected().equals(castOther.getPOptSelected()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPOptOptionId() == null ? 0 : this.getPOptOptionId().hashCode() );
         result = 37 * result + ( getPOptProductId() == null ? 0 : this.getPOptProductId().hashCode() );
         result = 37 * result + ( getPOptOrderByValue() == null ? 0 : this.getPOptOrderByValue().hashCode() );
         result = 37 * result + ( getPOptPriceChange() == null ? 0 : this.getPOptPriceChange().hashCode() );
         result = 37 * result + ( getPOptWeightChange() == null ? 0 : this.getPOptWeightChange().hashCode() );
         result = 37 * result + ( getPOptSelected() == null ? 0 : this.getPOptSelected().hashCode() );
         return result;
   }   


}


