package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1



/**
 * ProductCategoryLink generated by hbm2java
 */
public class ProductCategoryLink  implements java.io.Serializable {


     private ProductCategoryLinkId id;

    public ProductCategoryLink() {
    }

    public ProductCategoryLink(ProductCategoryLinkId id) {
       this.id = id;
    }
   
    public ProductCategoryLinkId getId() {
        return this.id;
    }
    
    public void setId(ProductCategoryLinkId id) {
        this.id = id;
    }




}


