package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1



/**
 * ProductOptionGroupLinkId generated by hbm2java
 */
public class ProductOptionGroupLinkId  implements java.io.Serializable {


     private Integer POptgProductId;
     private Integer POptgOptionGroupId;
     private Integer POptgOrderByValue;

    public ProductOptionGroupLinkId() {
    }

    public ProductOptionGroupLinkId(Integer POptgProductId, Integer POptgOptionGroupId, Integer POptgOrderByValue) {
       this.POptgProductId = POptgProductId;
       this.POptgOptionGroupId = POptgOptionGroupId;
       this.POptgOrderByValue = POptgOrderByValue;
    }
   
    public Integer getPOptgProductId() {
        return this.POptgProductId;
    }
    
    public void setPOptgProductId(Integer POptgProductId) {
        this.POptgProductId = POptgProductId;
    }
    public Integer getPOptgOptionGroupId() {
        return this.POptgOptionGroupId;
    }
    
    public void setPOptgOptionGroupId(Integer POptgOptionGroupId) {
        this.POptgOptionGroupId = POptgOptionGroupId;
    }
    public Integer getPOptgOrderByValue() {
        return this.POptgOrderByValue;
    }
    
    public void setPOptgOrderByValue(Integer POptgOrderByValue) {
        this.POptgOrderByValue = POptgOrderByValue;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductOptionGroupLinkId) ) return false;
		 ProductOptionGroupLinkId castOther = ( ProductOptionGroupLinkId ) other; 
         
		 return ( (this.getPOptgProductId()==castOther.getPOptgProductId()) || ( this.getPOptgProductId()!=null && castOther.getPOptgProductId()!=null && this.getPOptgProductId().equals(castOther.getPOptgProductId()) ) )
 && ( (this.getPOptgOptionGroupId()==castOther.getPOptgOptionGroupId()) || ( this.getPOptgOptionGroupId()!=null && castOther.getPOptgOptionGroupId()!=null && this.getPOptgOptionGroupId().equals(castOther.getPOptgOptionGroupId()) ) )
 && ( (this.getPOptgOrderByValue()==castOther.getPOptgOrderByValue()) || ( this.getPOptgOrderByValue()!=null && castOther.getPOptgOrderByValue()!=null && this.getPOptgOrderByValue().equals(castOther.getPOptgOrderByValue()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPOptgProductId() == null ? 0 : this.getPOptgProductId().hashCode() );
         result = 37 * result + ( getPOptgOptionGroupId() == null ? 0 : this.getPOptgOptionGroupId().hashCode() );
         result = 37 * result + ( getPOptgOrderByValue() == null ? 0 : this.getPOptgOrderByValue().hashCode() );
         return result;
   }   


}


