package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private int PId;
     private Serializable PLive;
     private Serializable PName1;
     private Serializable PName2;
     private Serializable PName3;
     private Serializable PName4;
     private Serializable PName5;
     private Serializable PDesc1;
     private Serializable PDesc2;
     private Serializable PDesc3;
     private Serializable PDesc4;
     private Serializable PDesc5;
     private Serializable PStrapLine1;
     private Serializable PStrapLine2;
     private Serializable PStrapLine3;
     private Serializable PStrapLine4;
     private Serializable PStrapLine5;
     private Serializable PSpecTable1;
     private Serializable PSpecTable2;
     private Serializable PSpecTable3;
     private Serializable PSpecTable4;
     private Serializable PSpecTable5;
     private Serializable PHyperlink1;
     private Serializable PHyperlink2;
     private Serializable PHyperlink3;
     private Serializable PHyperlink4;
     private Serializable PHyperlink5;
     private Integer PFeatured;
     private Double POrderByValue;
     private Serializable POrderVersionsBy;
     private Serializable PVersionDisplayType;
     private Serializable PReviews;
     private Integer PSupplierId;
     private Serializable PType;
     private Integer PCustomerGroupId;
     private Double PAverageRating;

    public Products() {
    }

	
    public Products(int PId) {
        this.PId = PId;
    }
    public Products(int PId, Serializable PLive, Serializable PName1, Serializable PName2, Serializable PName3, Serializable PName4, Serializable PName5, Serializable PDesc1, Serializable PDesc2, Serializable PDesc3, Serializable PDesc4, Serializable PDesc5, Serializable PStrapLine1, Serializable PStrapLine2, Serializable PStrapLine3, Serializable PStrapLine4, Serializable PStrapLine5, Serializable PSpecTable1, Serializable PSpecTable2, Serializable PSpecTable3, Serializable PSpecTable4, Serializable PSpecTable5, Serializable PHyperlink1, Serializable PHyperlink2, Serializable PHyperlink3, Serializable PHyperlink4, Serializable PHyperlink5, Integer PFeatured, Double POrderByValue, Serializable POrderVersionsBy, Serializable PVersionDisplayType, Serializable PReviews, Integer PSupplierId, Serializable PType, Integer PCustomerGroupId, Double PAverageRating) {
       this.PId = PId;
       this.PLive = PLive;
       this.PName1 = PName1;
       this.PName2 = PName2;
       this.PName3 = PName3;
       this.PName4 = PName4;
       this.PName5 = PName5;
       this.PDesc1 = PDesc1;
       this.PDesc2 = PDesc2;
       this.PDesc3 = PDesc3;
       this.PDesc4 = PDesc4;
       this.PDesc5 = PDesc5;
       this.PStrapLine1 = PStrapLine1;
       this.PStrapLine2 = PStrapLine2;
       this.PStrapLine3 = PStrapLine3;
       this.PStrapLine4 = PStrapLine4;
       this.PStrapLine5 = PStrapLine5;
       this.PSpecTable1 = PSpecTable1;
       this.PSpecTable2 = PSpecTable2;
       this.PSpecTable3 = PSpecTable3;
       this.PSpecTable4 = PSpecTable4;
       this.PSpecTable5 = PSpecTable5;
       this.PHyperlink1 = PHyperlink1;
       this.PHyperlink2 = PHyperlink2;
       this.PHyperlink3 = PHyperlink3;
       this.PHyperlink4 = PHyperlink4;
       this.PHyperlink5 = PHyperlink5;
       this.PFeatured = PFeatured;
       this.POrderByValue = POrderByValue;
       this.POrderVersionsBy = POrderVersionsBy;
       this.PVersionDisplayType = PVersionDisplayType;
       this.PReviews = PReviews;
       this.PSupplierId = PSupplierId;
       this.PType = PType;
       this.PCustomerGroupId = PCustomerGroupId;
       this.PAverageRating = PAverageRating;
    }
   
    public int getPId() {
        return this.PId;
    }
    
    public void setPId(int PId) {
        this.PId = PId;
    }
    public Serializable getPLive() {
        return this.PLive;
    }
    
    public void setPLive(Serializable PLive) {
        this.PLive = PLive;
    }
    public Serializable getPName1() {
        return this.PName1;
    }
    
    public void setPName1(Serializable PName1) {
        this.PName1 = PName1;
    }
    public Serializable getPName2() {
        return this.PName2;
    }
    
    public void setPName2(Serializable PName2) {
        this.PName2 = PName2;
    }
    public Serializable getPName3() {
        return this.PName3;
    }
    
    public void setPName3(Serializable PName3) {
        this.PName3 = PName3;
    }
    public Serializable getPName4() {
        return this.PName4;
    }
    
    public void setPName4(Serializable PName4) {
        this.PName4 = PName4;
    }
    public Serializable getPName5() {
        return this.PName5;
    }
    
    public void setPName5(Serializable PName5) {
        this.PName5 = PName5;
    }
    public Serializable getPDesc1() {
        return this.PDesc1;
    }
    
    public void setPDesc1(Serializable PDesc1) {
        this.PDesc1 = PDesc1;
    }
    public Serializable getPDesc2() {
        return this.PDesc2;
    }
    
    public void setPDesc2(Serializable PDesc2) {
        this.PDesc2 = PDesc2;
    }
    public Serializable getPDesc3() {
        return this.PDesc3;
    }
    
    public void setPDesc3(Serializable PDesc3) {
        this.PDesc3 = PDesc3;
    }
    public Serializable getPDesc4() {
        return this.PDesc4;
    }
    
    public void setPDesc4(Serializable PDesc4) {
        this.PDesc4 = PDesc4;
    }
    public Serializable getPDesc5() {
        return this.PDesc5;
    }
    
    public void setPDesc5(Serializable PDesc5) {
        this.PDesc5 = PDesc5;
    }
    public Serializable getPStrapLine1() {
        return this.PStrapLine1;
    }
    
    public void setPStrapLine1(Serializable PStrapLine1) {
        this.PStrapLine1 = PStrapLine1;
    }
    public Serializable getPStrapLine2() {
        return this.PStrapLine2;
    }
    
    public void setPStrapLine2(Serializable PStrapLine2) {
        this.PStrapLine2 = PStrapLine2;
    }
    public Serializable getPStrapLine3() {
        return this.PStrapLine3;
    }
    
    public void setPStrapLine3(Serializable PStrapLine3) {
        this.PStrapLine3 = PStrapLine3;
    }
    public Serializable getPStrapLine4() {
        return this.PStrapLine4;
    }
    
    public void setPStrapLine4(Serializable PStrapLine4) {
        this.PStrapLine4 = PStrapLine4;
    }
    public Serializable getPStrapLine5() {
        return this.PStrapLine5;
    }
    
    public void setPStrapLine5(Serializable PStrapLine5) {
        this.PStrapLine5 = PStrapLine5;
    }
    public Serializable getPSpecTable1() {
        return this.PSpecTable1;
    }
    
    public void setPSpecTable1(Serializable PSpecTable1) {
        this.PSpecTable1 = PSpecTable1;
    }
    public Serializable getPSpecTable2() {
        return this.PSpecTable2;
    }
    
    public void setPSpecTable2(Serializable PSpecTable2) {
        this.PSpecTable2 = PSpecTable2;
    }
    public Serializable getPSpecTable3() {
        return this.PSpecTable3;
    }
    
    public void setPSpecTable3(Serializable PSpecTable3) {
        this.PSpecTable3 = PSpecTable3;
    }
    public Serializable getPSpecTable4() {
        return this.PSpecTable4;
    }
    
    public void setPSpecTable4(Serializable PSpecTable4) {
        this.PSpecTable4 = PSpecTable4;
    }
    public Serializable getPSpecTable5() {
        return this.PSpecTable5;
    }
    
    public void setPSpecTable5(Serializable PSpecTable5) {
        this.PSpecTable5 = PSpecTable5;
    }
    public Serializable getPHyperlink1() {
        return this.PHyperlink1;
    }
    
    public void setPHyperlink1(Serializable PHyperlink1) {
        this.PHyperlink1 = PHyperlink1;
    }
    public Serializable getPHyperlink2() {
        return this.PHyperlink2;
    }
    
    public void setPHyperlink2(Serializable PHyperlink2) {
        this.PHyperlink2 = PHyperlink2;
    }
    public Serializable getPHyperlink3() {
        return this.PHyperlink3;
    }
    
    public void setPHyperlink3(Serializable PHyperlink3) {
        this.PHyperlink3 = PHyperlink3;
    }
    public Serializable getPHyperlink4() {
        return this.PHyperlink4;
    }
    
    public void setPHyperlink4(Serializable PHyperlink4) {
        this.PHyperlink4 = PHyperlink4;
    }
    public Serializable getPHyperlink5() {
        return this.PHyperlink5;
    }
    
    public void setPHyperlink5(Serializable PHyperlink5) {
        this.PHyperlink5 = PHyperlink5;
    }
    public Integer getPFeatured() {
        return this.PFeatured;
    }
    
    public void setPFeatured(Integer PFeatured) {
        this.PFeatured = PFeatured;
    }
    public Double getPOrderByValue() {
        return this.POrderByValue;
    }
    
    public void setPOrderByValue(Double POrderByValue) {
        this.POrderByValue = POrderByValue;
    }
    public Serializable getPOrderVersionsBy() {
        return this.POrderVersionsBy;
    }
    
    public void setPOrderVersionsBy(Serializable POrderVersionsBy) {
        this.POrderVersionsBy = POrderVersionsBy;
    }
    public Serializable getPVersionDisplayType() {
        return this.PVersionDisplayType;
    }
    
    public void setPVersionDisplayType(Serializable PVersionDisplayType) {
        this.PVersionDisplayType = PVersionDisplayType;
    }
    public Serializable getPReviews() {
        return this.PReviews;
    }
    
    public void setPReviews(Serializable PReviews) {
        this.PReviews = PReviews;
    }
    public Integer getPSupplierId() {
        return this.PSupplierId;
    }
    
    public void setPSupplierId(Integer PSupplierId) {
        this.PSupplierId = PSupplierId;
    }
    public Serializable getPType() {
        return this.PType;
    }
    
    public void setPType(Serializable PType) {
        this.PType = PType;
    }
    public Integer getPCustomerGroupId() {
        return this.PCustomerGroupId;
    }
    
    public void setPCustomerGroupId(Integer PCustomerGroupId) {
        this.PCustomerGroupId = PCustomerGroupId;
    }
    public Double getPAverageRating() {
        return this.PAverageRating;
    }
    
    public void setPAverageRating(Double PAverageRating) {
        this.PAverageRating = PAverageRating;
    }




}


