package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1



/**
 * ProductOptionLink generated by hbm2java
 */
public class ProductOptionLink  implements java.io.Serializable {


     private ProductOptionLinkId id;

    public ProductOptionLink() {
    }

    public ProductOptionLink(ProductOptionLinkId id) {
       this.id = id;
    }
   
    public ProductOptionLinkId getId() {
        return this.id;
    }
    
    public void setId(ProductOptionLinkId id) {
        this.id = id;
    }




}


