package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * Promotions generated by hbm2java
 */
public class Promotions  implements java.io.Serializable {


     private int promId;
     private Serializable promName1;
     private Serializable promName2;
     private Serializable promName3;
     private Serializable promName4;
     private Serializable promName5;
     private Date promStartDate;
     private Date promEndDate;
     private Serializable promType1;
     private Integer promVersionId1;
     private Double promValue1;
     private Serializable promType2;
     private Integer promVersionId2;
     private Double promValue2;
     private Serializable promLive;
     private Integer promOrderByValue;
     private Integer promMaxQuantity;

    public Promotions() {
    }

	
    public Promotions(int promId) {
        this.promId = promId;
    }
    public Promotions(int promId, Serializable promName1, Serializable promName2, Serializable promName3, Serializable promName4, Serializable promName5, Date promStartDate, Date promEndDate, Serializable promType1, Integer promVersionId1, Double promValue1, Serializable promType2, Integer promVersionId2, Double promValue2, Serializable promLive, Integer promOrderByValue, Integer promMaxQuantity) {
       this.promId = promId;
       this.promName1 = promName1;
       this.promName2 = promName2;
       this.promName3 = promName3;
       this.promName4 = promName4;
       this.promName5 = promName5;
       this.promStartDate = promStartDate;
       this.promEndDate = promEndDate;
       this.promType1 = promType1;
       this.promVersionId1 = promVersionId1;
       this.promValue1 = promValue1;
       this.promType2 = promType2;
       this.promVersionId2 = promVersionId2;
       this.promValue2 = promValue2;
       this.promLive = promLive;
       this.promOrderByValue = promOrderByValue;
       this.promMaxQuantity = promMaxQuantity;
    }
   
    public int getPromId() {
        return this.promId;
    }
    
    public void setPromId(int promId) {
        this.promId = promId;
    }
    public Serializable getPromName1() {
        return this.promName1;
    }
    
    public void setPromName1(Serializable promName1) {
        this.promName1 = promName1;
    }
    public Serializable getPromName2() {
        return this.promName2;
    }
    
    public void setPromName2(Serializable promName2) {
        this.promName2 = promName2;
    }
    public Serializable getPromName3() {
        return this.promName3;
    }
    
    public void setPromName3(Serializable promName3) {
        this.promName3 = promName3;
    }
    public Serializable getPromName4() {
        return this.promName4;
    }
    
    public void setPromName4(Serializable promName4) {
        this.promName4 = promName4;
    }
    public Serializable getPromName5() {
        return this.promName5;
    }
    
    public void setPromName5(Serializable promName5) {
        this.promName5 = promName5;
    }
    public Date getPromStartDate() {
        return this.promStartDate;
    }
    
    public void setPromStartDate(Date promStartDate) {
        this.promStartDate = promStartDate;
    }
    public Date getPromEndDate() {
        return this.promEndDate;
    }
    
    public void setPromEndDate(Date promEndDate) {
        this.promEndDate = promEndDate;
    }
    public Serializable getPromType1() {
        return this.promType1;
    }
    
    public void setPromType1(Serializable promType1) {
        this.promType1 = promType1;
    }
    public Integer getPromVersionId1() {
        return this.promVersionId1;
    }
    
    public void setPromVersionId1(Integer promVersionId1) {
        this.promVersionId1 = promVersionId1;
    }
    public Double getPromValue1() {
        return this.promValue1;
    }
    
    public void setPromValue1(Double promValue1) {
        this.promValue1 = promValue1;
    }
    public Serializable getPromType2() {
        return this.promType2;
    }
    
    public void setPromType2(Serializable promType2) {
        this.promType2 = promType2;
    }
    public Integer getPromVersionId2() {
        return this.promVersionId2;
    }
    
    public void setPromVersionId2(Integer promVersionId2) {
        this.promVersionId2 = promVersionId2;
    }
    public Double getPromValue2() {
        return this.promValue2;
    }
    
    public void setPromValue2(Double promValue2) {
        this.promValue2 = promValue2;
    }
    public Serializable getPromLive() {
        return this.promLive;
    }
    
    public void setPromLive(Serializable promLive) {
        this.promLive = promLive;
    }
    public Integer getPromOrderByValue() {
        return this.promOrderByValue;
    }
    
    public void setPromOrderByValue(Integer promOrderByValue) {
        this.promOrderByValue = promOrderByValue;
    }
    public Integer getPromMaxQuantity() {
        return this.promMaxQuantity;
    }
    
    public void setPromMaxQuantity(Integer promMaxQuantity) {
        this.promMaxQuantity = promMaxQuantity;
    }




}


