package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1



/**
 * QuantityDiscounts generated by hbm2java
 */
public class QuantityDiscounts  implements java.io.Serializable {


     private int qdId;
     private Integer qdVersionId;
     private Integer qdQuantity;
     private Double qdPrice;

    public QuantityDiscounts() {
    }

	
    public QuantityDiscounts(int qdId) {
        this.qdId = qdId;
    }
    public QuantityDiscounts(int qdId, Integer qdVersionId, Integer qdQuantity, Double qdPrice) {
       this.qdId = qdId;
       this.qdVersionId = qdVersionId;
       this.qdQuantity = qdQuantity;
       this.qdPrice = qdPrice;
    }
   
    public int getQdId() {
        return this.qdId;
    }
    
    public void setQdId(int qdId) {
        this.qdId = qdId;
    }
    public Integer getQdVersionId() {
        return this.qdVersionId;
    }
    
    public void setQdVersionId(Integer qdVersionId) {
        this.qdVersionId = qdVersionId;
    }
    public Integer getQdQuantity() {
        return this.qdQuantity;
    }
    
    public void setQdQuantity(Integer qdQuantity) {
        this.qdQuantity = qdQuantity;
    }
    public Double getQdPrice() {
        return this.qdPrice;
    }
    
    public void setQdPrice(Double qdPrice) {
        this.qdPrice = qdPrice;
    }




}


