package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1



/**
 * RelatedProducts generated by hbm2java
 */
public class RelatedProducts  implements java.io.Serializable {


     private int rpId;
     private Integer rpParentId;
     private Integer rpChildId;

    public RelatedProducts() {
    }

	
    public RelatedProducts(int rpId) {
        this.rpId = rpId;
    }
    public RelatedProducts(int rpId, Integer rpParentId, Integer rpChildId) {
       this.rpId = rpId;
       this.rpParentId = rpParentId;
       this.rpChildId = rpChildId;
    }
   
    public int getRpId() {
        return this.rpId;
    }
    
    public void setRpId(int rpId) {
        this.rpId = rpId;
    }
    public Integer getRpParentId() {
        return this.rpParentId;
    }
    
    public void setRpParentId(Integer rpParentId) {
        this.rpParentId = rpParentId;
    }
    public Integer getRpChildId() {
        return this.rpChildId;
    }
    
    public void setRpChildId(Integer rpChildId) {
        this.rpChildId = rpChildId;
    }




}


