package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * Reviews generated by hbm2java
 */
public class Reviews  implements java.io.Serializable {


     private int revId;
     private Integer revProductId;
     private Integer revVersionId;
     private Integer revLanguageId;
     private Integer revCustomerId;
     private Serializable revTitle;
     private Serializable revText;
     private Integer revRating;
     private Serializable revName;
     private Serializable revEmail;
     private Serializable revLocation;
     private Serializable revLive;
     private Date revDateCreated;
     private Date revDateLastUpdated;

    public Reviews() {
    }

	
    public Reviews(int revId) {
        this.revId = revId;
    }
    public Reviews(int revId, Integer revProductId, Integer revVersionId, Integer revLanguageId, Integer revCustomerId, Serializable revTitle, Serializable revText, Integer revRating, Serializable revName, Serializable revEmail, Serializable revLocation, Serializable revLive, Date revDateCreated, Date revDateLastUpdated) {
       this.revId = revId;
       this.revProductId = revProductId;
       this.revVersionId = revVersionId;
       this.revLanguageId = revLanguageId;
       this.revCustomerId = revCustomerId;
       this.revTitle = revTitle;
       this.revText = revText;
       this.revRating = revRating;
       this.revName = revName;
       this.revEmail = revEmail;
       this.revLocation = revLocation;
       this.revLive = revLive;
       this.revDateCreated = revDateCreated;
       this.revDateLastUpdated = revDateLastUpdated;
    }
   
    public int getRevId() {
        return this.revId;
    }
    
    public void setRevId(int revId) {
        this.revId = revId;
    }
    public Integer getRevProductId() {
        return this.revProductId;
    }
    
    public void setRevProductId(Integer revProductId) {
        this.revProductId = revProductId;
    }
    public Integer getRevVersionId() {
        return this.revVersionId;
    }
    
    public void setRevVersionId(Integer revVersionId) {
        this.revVersionId = revVersionId;
    }
    public Integer getRevLanguageId() {
        return this.revLanguageId;
    }
    
    public void setRevLanguageId(Integer revLanguageId) {
        this.revLanguageId = revLanguageId;
    }
    public Integer getRevCustomerId() {
        return this.revCustomerId;
    }
    
    public void setRevCustomerId(Integer revCustomerId) {
        this.revCustomerId = revCustomerId;
    }
    public Serializable getRevTitle() {
        return this.revTitle;
    }
    
    public void setRevTitle(Serializable revTitle) {
        this.revTitle = revTitle;
    }
    public Serializable getRevText() {
        return this.revText;
    }
    
    public void setRevText(Serializable revText) {
        this.revText = revText;
    }
    public Integer getRevRating() {
        return this.revRating;
    }
    
    public void setRevRating(Integer revRating) {
        this.revRating = revRating;
    }
    public Serializable getRevName() {
        return this.revName;
    }
    
    public void setRevName(Serializable revName) {
        this.revName = revName;
    }
    public Serializable getRevEmail() {
        return this.revEmail;
    }
    
    public void setRevEmail(Serializable revEmail) {
        this.revEmail = revEmail;
    }
    public Serializable getRevLocation() {
        return this.revLocation;
    }
    
    public void setRevLocation(Serializable revLocation) {
        this.revLocation = revLocation;
    }
    public Serializable getRevLive() {
        return this.revLive;
    }
    
    public void setRevLive(Serializable revLive) {
        this.revLive = revLive;
    }
    public Date getRevDateCreated() {
        return this.revDateCreated;
    }
    
    public void setRevDateCreated(Date revDateCreated) {
        this.revDateCreated = revDateCreated;
    }
    public Date getRevDateLastUpdated() {
        return this.revDateLastUpdated;
    }
    
    public void setRevDateLastUpdated(Date revDateLastUpdated) {
        this.revDateLastUpdated = revDateLastUpdated;
    }




}


