package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * SavedExports generated by hbm2java
 */
public class SavedExports  implements java.io.Serializable {


     private int exportId;
     private Serializable exportName;
     private Date exportDate;
     private Serializable exportDetails;

    public SavedExports() {
    }

	
    public SavedExports(int exportId) {
        this.exportId = exportId;
    }
    public SavedExports(int exportId, Serializable exportName, Date exportDate, Serializable exportDetails) {
       this.exportId = exportId;
       this.exportName = exportName;
       this.exportDate = exportDate;
       this.exportDetails = exportDetails;
    }
   
    public int getExportId() {
        return this.exportId;
    }
    
    public void setExportId(int exportId) {
        this.exportId = exportId;
    }
    public Serializable getExportName() {
        return this.exportName;
    }
    
    public void setExportName(Serializable exportName) {
        this.exportName = exportName;
    }
    public Date getExportDate() {
        return this.exportDate;
    }
    
    public void setExportDate(Date exportDate) {
        this.exportDate = exportDate;
    }
    public Serializable getExportDetails() {
        return this.exportDetails;
    }
    
    public void setExportDetails(Serializable exportDetails) {
        this.exportDetails = exportDetails;
    }




}


