package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * SaveBasket generated by hbm2java
 */
public class SaveBasket  implements java.io.Serializable {


     private int bsktId;
     private Integer bsktCustomerId;
     private Serializable bsktName;
     private Serializable bsktItems;
     private Serializable bsktQuantity;
     private Serializable bsktOptionGroups;
     private Serializable bsktOptions;
     private Date bsktDateTime;

    public SaveBasket() {
    }

	
    public SaveBasket(int bsktId) {
        this.bsktId = bsktId;
    }
    public SaveBasket(int bsktId, Integer bsktCustomerId, Serializable bsktName, Serializable bsktItems, Serializable bsktQuantity, Serializable bsktOptionGroups, Serializable bsktOptions, Date bsktDateTime) {
       this.bsktId = bsktId;
       this.bsktCustomerId = bsktCustomerId;
       this.bsktName = bsktName;
       this.bsktItems = bsktItems;
       this.bsktQuantity = bsktQuantity;
       this.bsktOptionGroups = bsktOptionGroups;
       this.bsktOptions = bsktOptions;
       this.bsktDateTime = bsktDateTime;
    }
   
    public int getBsktId() {
        return this.bsktId;
    }
    
    public void setBsktId(int bsktId) {
        this.bsktId = bsktId;
    }
    public Integer getBsktCustomerId() {
        return this.bsktCustomerId;
    }
    
    public void setBsktCustomerId(Integer bsktCustomerId) {
        this.bsktCustomerId = bsktCustomerId;
    }
    public Serializable getBsktName() {
        return this.bsktName;
    }
    
    public void setBsktName(Serializable bsktName) {
        this.bsktName = bsktName;
    }
    public Serializable getBsktItems() {
        return this.bsktItems;
    }
    
    public void setBsktItems(Serializable bsktItems) {
        this.bsktItems = bsktItems;
    }
    public Serializable getBsktQuantity() {
        return this.bsktQuantity;
    }
    
    public void setBsktQuantity(Serializable bsktQuantity) {
        this.bsktQuantity = bsktQuantity;
    }
    public Serializable getBsktOptionGroups() {
        return this.bsktOptionGroups;
    }
    
    public void setBsktOptionGroups(Serializable bsktOptionGroups) {
        this.bsktOptionGroups = bsktOptionGroups;
    }
    public Serializable getBsktOptions() {
        return this.bsktOptions;
    }
    
    public void setBsktOptions(Serializable bsktOptions) {
        this.bsktOptions = bsktOptions;
    }
    public Date getBsktDateTime() {
        return this.bsktDateTime;
    }
    
    public void setBsktDateTime(Date bsktDateTime) {
        this.bsktDateTime = bsktDateTime;
    }




}


