package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * SessionValuesId generated by hbm2java
 */
public class SessionValuesId  implements java.io.Serializable {


     private int sessvId;
     private Integer sessvSessionId;
     private Serializable sessvName;
     private Serializable sessvValue;
     private Integer sessvExpiry;

    public SessionValuesId() {
    }

	
    public SessionValuesId(int sessvId, Serializable sessvName, Serializable sessvValue) {
        this.sessvId = sessvId;
        this.sessvName = sessvName;
        this.sessvValue = sessvValue;
    }
    public SessionValuesId(int sessvId, Integer sessvSessionId, Serializable sessvName, Serializable sessvValue, Integer sessvExpiry) {
       this.sessvId = sessvId;
       this.sessvSessionId = sessvSessionId;
       this.sessvName = sessvName;
       this.sessvValue = sessvValue;
       this.sessvExpiry = sessvExpiry;
    }
   
    public int getSessvId() {
        return this.sessvId;
    }
    
    public void setSessvId(int sessvId) {
        this.sessvId = sessvId;
    }
    public Integer getSessvSessionId() {
        return this.sessvSessionId;
    }
    
    public void setSessvSessionId(Integer sessvSessionId) {
        this.sessvSessionId = sessvSessionId;
    }
    public Serializable getSessvName() {
        return this.sessvName;
    }
    
    public void setSessvName(Serializable sessvName) {
        this.sessvName = sessvName;
    }
    public Serializable getSessvValue() {
        return this.sessvValue;
    }
    
    public void setSessvValue(Serializable sessvValue) {
        this.sessvValue = sessvValue;
    }
    public Integer getSessvExpiry() {
        return this.sessvExpiry;
    }
    
    public void setSessvExpiry(Integer sessvExpiry) {
        this.sessvExpiry = sessvExpiry;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SessionValuesId) ) return false;
		 SessionValuesId castOther = ( SessionValuesId ) other; 
         
		 return (this.getSessvId()==castOther.getSessvId())
 && ( (this.getSessvSessionId()==castOther.getSessvSessionId()) || ( this.getSessvSessionId()!=null && castOther.getSessvSessionId()!=null && this.getSessvSessionId().equals(castOther.getSessvSessionId()) ) )
 && ( (this.getSessvName()==castOther.getSessvName()) || ( this.getSessvName()!=null && castOther.getSessvName()!=null && this.getSessvName().equals(castOther.getSessvName()) ) )
 && ( (this.getSessvValue()==castOther.getSessvValue()) || ( this.getSessvValue()!=null && castOther.getSessvValue()!=null && this.getSessvValue().equals(castOther.getSessvValue()) ) )
 && ( (this.getSessvExpiry()==castOther.getSessvExpiry()) || ( this.getSessvExpiry()!=null && castOther.getSessvExpiry()!=null && this.getSessvExpiry().equals(castOther.getSessvExpiry()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSessvId();
         result = 37 * result + ( getSessvSessionId() == null ? 0 : this.getSessvSessionId().hashCode() );
         result = 37 * result + ( getSessvName() == null ? 0 : this.getSessvName().hashCode() );
         result = 37 * result + ( getSessvValue() == null ? 0 : this.getSessvValue().hashCode() );
         result = 37 * result + ( getSessvExpiry() == null ? 0 : this.getSessvExpiry().hashCode() );
         return result;
   }   


}


