package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1



/**
 * SessionValues generated by hbm2java
 */
public class SessionValues  implements java.io.Serializable {


     private SessionValuesId id;

    public SessionValues() {
    }

    public SessionValues(SessionValuesId id) {
       this.id = id;
    }
   
    public SessionValuesId getId() {
        return this.id;
    }
    
    public void setId(SessionValuesId id) {
        this.id = id;
    }




}


