package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * Sessions generated by hbm2java
 */
public class Sessions  implements java.io.Serializable {


     private int sessId;
     private Serializable sessCode;
     private Serializable sessIp;
     private Date sessDateCreated;
     private Date sessDateLastUpdated;
     private Integer sessExpiry;

    public Sessions() {
    }

	
    public Sessions(int sessId, Serializable sessCode, Serializable sessIp, Date sessDateCreated) {
        this.sessId = sessId;
        this.sessCode = sessCode;
        this.sessIp = sessIp;
        this.sessDateCreated = sessDateCreated;
    }
    public Sessions(int sessId, Serializable sessCode, Serializable sessIp, Date sessDateCreated, Date sessDateLastUpdated, Integer sessExpiry) {
       this.sessId = sessId;
       this.sessCode = sessCode;
       this.sessIp = sessIp;
       this.sessDateCreated = sessDateCreated;
       this.sessDateLastUpdated = sessDateLastUpdated;
       this.sessExpiry = sessExpiry;
    }
   
    public int getSessId() {
        return this.sessId;
    }
    
    public void setSessId(int sessId) {
        this.sessId = sessId;
    }
    public Serializable getSessCode() {
        return this.sessCode;
    }
    
    public void setSessCode(Serializable sessCode) {
        this.sessCode = sessCode;
    }
    public Serializable getSessIp() {
        return this.sessIp;
    }
    
    public void setSessIp(Serializable sessIp) {
        this.sessIp = sessIp;
    }
    public Date getSessDateCreated() {
        return this.sessDateCreated;
    }
    
    public void setSessDateCreated(Date sessDateCreated) {
        this.sessDateCreated = sessDateCreated;
    }
    public Date getSessDateLastUpdated() {
        return this.sessDateLastUpdated;
    }
    
    public void setSessDateLastUpdated(Date sessDateLastUpdated) {
        this.sessDateLastUpdated = sessDateLastUpdated;
    }
    public Integer getSessExpiry() {
        return this.sessExpiry;
    }
    
    public void setSessExpiry(Integer sessExpiry) {
        this.sessExpiry = sessExpiry;
    }




}


