package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1



/**
 * ShippingRates generated by hbm2java
 */
public class ShippingRates  implements java.io.Serializable {


     private int SId;
     private Integer SShippingMethodId;
     private Integer SShippingZoneId;
     private float SShippingRate;
     private float SBoundary;

    public ShippingRates() {
    }

	
    public ShippingRates(int SId, float SShippingRate, float SBoundary) {
        this.SId = SId;
        this.SShippingRate = SShippingRate;
        this.SBoundary = SBoundary;
    }
    public ShippingRates(int SId, Integer SShippingMethodId, Integer SShippingZoneId, float SShippingRate, float SBoundary) {
       this.SId = SId;
       this.SShippingMethodId = SShippingMethodId;
       this.SShippingZoneId = SShippingZoneId;
       this.SShippingRate = SShippingRate;
       this.SBoundary = SBoundary;
    }
   
    public int getSId() {
        return this.SId;
    }
    
    public void setSId(int SId) {
        this.SId = SId;
    }
    public Integer getSShippingMethodId() {
        return this.SShippingMethodId;
    }
    
    public void setSShippingMethodId(Integer SShippingMethodId) {
        this.SShippingMethodId = SShippingMethodId;
    }
    public Integer getSShippingZoneId() {
        return this.SShippingZoneId;
    }
    
    public void setSShippingZoneId(Integer SShippingZoneId) {
        this.SShippingZoneId = SShippingZoneId;
    }
    public float getSShippingRate() {
        return this.SShippingRate;
    }
    
    public void setSShippingRate(float SShippingRate) {
        this.SShippingRate = SShippingRate;
    }
    public float getSBoundary() {
        return this.SBoundary;
    }
    
    public void setSBoundary(float SBoundary) {
        this.SBoundary = SBoundary;
    }




}


