package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * ShippingMethods generated by hbm2java
 */
public class ShippingMethods  implements java.io.Serializable {


     private int smId;
     private Serializable smName1;
     private Serializable smName2;
     private Serializable smName3;
     private Serializable smName4;
     private Serializable smName5;
     private Serializable smDescription1;
     private Serializable smDescription2;
     private Serializable smDescription3;
     private Serializable smDescription4;
     private Serializable smDescription5;
     private Serializable smLive;
     private Integer smOrderByValue;

    public ShippingMethods() {
    }

	
    public ShippingMethods(int smId) {
        this.smId = smId;
    }
    public ShippingMethods(int smId, Serializable smName1, Serializable smName2, Serializable smName3, Serializable smName4, Serializable smName5, Serializable smDescription1, Serializable smDescription2, Serializable smDescription3, Serializable smDescription4, Serializable smDescription5, Serializable smLive, Integer smOrderByValue) {
       this.smId = smId;
       this.smName1 = smName1;
       this.smName2 = smName2;
       this.smName3 = smName3;
       this.smName4 = smName4;
       this.smName5 = smName5;
       this.smDescription1 = smDescription1;
       this.smDescription2 = smDescription2;
       this.smDescription3 = smDescription3;
       this.smDescription4 = smDescription4;
       this.smDescription5 = smDescription5;
       this.smLive = smLive;
       this.smOrderByValue = smOrderByValue;
    }
   
    public int getSmId() {
        return this.smId;
    }
    
    public void setSmId(int smId) {
        this.smId = smId;
    }
    public Serializable getSmName1() {
        return this.smName1;
    }
    
    public void setSmName1(Serializable smName1) {
        this.smName1 = smName1;
    }
    public Serializable getSmName2() {
        return this.smName2;
    }
    
    public void setSmName2(Serializable smName2) {
        this.smName2 = smName2;
    }
    public Serializable getSmName3() {
        return this.smName3;
    }
    
    public void setSmName3(Serializable smName3) {
        this.smName3 = smName3;
    }
    public Serializable getSmName4() {
        return this.smName4;
    }
    
    public void setSmName4(Serializable smName4) {
        this.smName4 = smName4;
    }
    public Serializable getSmName5() {
        return this.smName5;
    }
    
    public void setSmName5(Serializable smName5) {
        this.smName5 = smName5;
    }
    public Serializable getSmDescription1() {
        return this.smDescription1;
    }
    
    public void setSmDescription1(Serializable smDescription1) {
        this.smDescription1 = smDescription1;
    }
    public Serializable getSmDescription2() {
        return this.smDescription2;
    }
    
    public void setSmDescription2(Serializable smDescription2) {
        this.smDescription2 = smDescription2;
    }
    public Serializable getSmDescription3() {
        return this.smDescription3;
    }
    
    public void setSmDescription3(Serializable smDescription3) {
        this.smDescription3 = smDescription3;
    }
    public Serializable getSmDescription4() {
        return this.smDescription4;
    }
    
    public void setSmDescription4(Serializable smDescription4) {
        this.smDescription4 = smDescription4;
    }
    public Serializable getSmDescription5() {
        return this.smDescription5;
    }
    
    public void setSmDescription5(Serializable smDescription5) {
        this.smDescription5 = smDescription5;
    }
    public Serializable getSmLive() {
        return this.smLive;
    }
    
    public void setSmLive(Serializable smLive) {
        this.smLive = smLive;
    }
    public Integer getSmOrderByValue() {
        return this.smOrderByValue;
    }
    
    public void setSmOrderByValue(Integer smOrderByValue) {
        this.smOrderByValue = smOrderByValue;
    }




}


