package model.utils;
// Generated Mar 19, 2017 8:47:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Shippers generated by hbm2java
 */
public class Shippers {


     private int shipperId;
     private String companyName;
     private String phone;
     private Set orderses = new HashSet(0);

    public Shippers() {
    }

	
    public Shippers(int shipperId, String companyName) {
        this.shipperId = shipperId;
        this.companyName = companyName;
    }
    public Shippers(int shipperId, String companyName, String phone, Set orderses) {
       this.shipperId = shipperId;
       this.companyName = companyName;
       this.phone = phone;
       this.orderses = orderses;
    }
   
    public int getShipperId() {
        return this.shipperId;
    }
    
    public void setShipperId(int shipperId) {
        this.shipperId = shipperId;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


