package model.utils;
// Generated Mar 19, 2017 8:47:25 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Shippers generated by hbm2java
 */
public class Shippers  implements java.io.Serializable {


     private int shipperId;
     private Serializable companyName;
     private Serializable phone;
     private Set orderses = new HashSet(0);

    public Shippers() {
    }

	
    public Shippers(int shipperId, Serializable companyName) {
        this.shipperId = shipperId;
        this.companyName = companyName;
    }
    public Shippers(int shipperId, Serializable companyName, Serializable phone, Set orderses) {
       this.shipperId = shipperId;
       this.companyName = companyName;
       this.phone = phone;
       this.orderses = orderses;
    }
   
    public int getShipperId() {
        return this.shipperId;
    }
    
    public void setShipperId(int shipperId) {
        this.shipperId = shipperId;
    }
    public Serializable getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(Serializable companyName) {
        this.companyName = companyName;
    }
    public Serializable getPhone() {
        return this.phone;
    }
    
    public void setPhone(Serializable phone) {
        this.phone = phone;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


