package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Suppliers generated by hbm2java
 */
public class Suppliers  implements java.io.Serializable {


     private int supId;
     private Serializable supName;
     private Serializable supLive;

    public Suppliers() {
    }

	
    public Suppliers(int supId) {
        this.supId = supId;
    }
    public Suppliers(int supId, Serializable supName, Serializable supLive) {
       this.supId = supId;
       this.supName = supName;
       this.supLive = supLive;
    }
   
    public int getSupId() {
        return this.supId;
    }
    
    public void setSupId(int supId) {
        this.supId = supId;
    }
    public Serializable getSupName() {
        return this.supName;
    }
    
    public void setSupName(Serializable supName) {
        this.supName = supName;
    }
    public Serializable getSupLive() {
        return this.supLive;
    }
    
    public void setSupLive(Serializable supLive) {
        this.supLive = supLive;
    }




}


