package model.utils;
// Generated Mar 19, 2017 8:47:25 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Territories generated by hbm2java
 */
public class Territories  implements java.io.Serializable {


     private Serializable territoryId;
     private Region region;
     private Serializable territoryDescription;
     private Set employeeses = new HashSet(0);

    public Territories() {
    }

	
    public Territories(Serializable territoryId, Region region, Serializable territoryDescription) {
        this.territoryId = territoryId;
        this.region = region;
        this.territoryDescription = territoryDescription;
    }
    public Territories(Serializable territoryId, Region region, Serializable territoryDescription, Set employeeses) {
       this.territoryId = territoryId;
       this.region = region;
       this.territoryDescription = territoryDescription;
       this.employeeses = employeeses;
    }
   
    public Serializable getTerritoryId() {
        return this.territoryId;
    }
    
    public void setTerritoryId(Serializable territoryId) {
        this.territoryId = territoryId;
    }
    public Region getRegion() {
        return this.region;
    }
    
    public void setRegion(Region region) {
        this.region = region;
    }
    public Serializable getTerritoryDescription() {
        return this.territoryDescription;
    }
    
    public void setTerritoryDescription(Serializable territoryDescription) {
        this.territoryDescription = territoryDescription;
    }
    public Set getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set employeeses) {
        this.employeeses = employeeses;
    }




}


