package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1



/**
 * VersionOptionLink generated by hbm2java
 */
public class VersionOptionLink  implements java.io.Serializable {


     private VersionOptionLinkId id;

    public VersionOptionLink() {
    }

    public VersionOptionLink(VersionOptionLinkId id) {
       this.id = id;
    }
   
    public VersionOptionLinkId getId() {
        return this.id;
    }
    
    public void setId(VersionOptionLinkId id) {
        this.id = id;
    }




}


