package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Versions generated by hbm2java
 */
public class Versions  implements java.io.Serializable {


     private int VId;
     private Serializable VName1;
     private Serializable VName2;
     private Serializable VName3;
     private Serializable VName4;
     private Serializable VName5;
     private Serializable VCodeNumber;
     private Integer VProductId;
     private Double VPrice;
     private Double VTax;
     private Double VWeight;
     private Integer VDeliveryTime;
     private Integer VQuantity;
     private Integer VQuantityWarnLevel;
     private Serializable VDesc1;
     private Serializable VDesc2;
     private Serializable VDesc3;
     private Serializable VDesc4;
     private Serializable VDesc5;
     private Serializable VLive;
     private Serializable VDownLoadInfo;
     private Serializable VDownloadType;
     private Integer VOrderByValue;
     private Double VRrp;
     private Serializable VType;
     private Integer VCustomerGroupId;

    public Versions() {
    }

	
    public Versions(int VId) {
        this.VId = VId;
    }
    public Versions(int VId, Serializable VName1, Serializable VName2, Serializable VName3, Serializable VName4, Serializable VName5, Serializable VCodeNumber, Integer VProductId, Double VPrice, Double VTax, Double VWeight, Integer VDeliveryTime, Integer VQuantity, Integer VQuantityWarnLevel, Serializable VDesc1, Serializable VDesc2, Serializable VDesc3, Serializable VDesc4, Serializable VDesc5, Serializable VLive, Serializable VDownLoadInfo, Serializable VDownloadType, Integer VOrderByValue, Double VRrp, Serializable VType, Integer VCustomerGroupId) {
       this.VId = VId;
       this.VName1 = VName1;
       this.VName2 = VName2;
       this.VName3 = VName3;
       this.VName4 = VName4;
       this.VName5 = VName5;
       this.VCodeNumber = VCodeNumber;
       this.VProductId = VProductId;
       this.VPrice = VPrice;
       this.VTax = VTax;
       this.VWeight = VWeight;
       this.VDeliveryTime = VDeliveryTime;
       this.VQuantity = VQuantity;
       this.VQuantityWarnLevel = VQuantityWarnLevel;
       this.VDesc1 = VDesc1;
       this.VDesc2 = VDesc2;
       this.VDesc3 = VDesc3;
       this.VDesc4 = VDesc4;
       this.VDesc5 = VDesc5;
       this.VLive = VLive;
       this.VDownLoadInfo = VDownLoadInfo;
       this.VDownloadType = VDownloadType;
       this.VOrderByValue = VOrderByValue;
       this.VRrp = VRrp;
       this.VType = VType;
       this.VCustomerGroupId = VCustomerGroupId;
    }
   
    public int getVId() {
        return this.VId;
    }
    
    public void setVId(int VId) {
        this.VId = VId;
    }
    public Serializable getVName1() {
        return this.VName1;
    }
    
    public void setVName1(Serializable VName1) {
        this.VName1 = VName1;
    }
    public Serializable getVName2() {
        return this.VName2;
    }
    
    public void setVName2(Serializable VName2) {
        this.VName2 = VName2;
    }
    public Serializable getVName3() {
        return this.VName3;
    }
    
    public void setVName3(Serializable VName3) {
        this.VName3 = VName3;
    }
    public Serializable getVName4() {
        return this.VName4;
    }
    
    public void setVName4(Serializable VName4) {
        this.VName4 = VName4;
    }
    public Serializable getVName5() {
        return this.VName5;
    }
    
    public void setVName5(Serializable VName5) {
        this.VName5 = VName5;
    }
    public Serializable getVCodeNumber() {
        return this.VCodeNumber;
    }
    
    public void setVCodeNumber(Serializable VCodeNumber) {
        this.VCodeNumber = VCodeNumber;
    }
    public Integer getVProductId() {
        return this.VProductId;
    }
    
    public void setVProductId(Integer VProductId) {
        this.VProductId = VProductId;
    }
    public Double getVPrice() {
        return this.VPrice;
    }
    
    public void setVPrice(Double VPrice) {
        this.VPrice = VPrice;
    }
    public Double getVTax() {
        return this.VTax;
    }
    
    public void setVTax(Double VTax) {
        this.VTax = VTax;
    }
    public Double getVWeight() {
        return this.VWeight;
    }
    
    public void setVWeight(Double VWeight) {
        this.VWeight = VWeight;
    }
    public Integer getVDeliveryTime() {
        return this.VDeliveryTime;
    }
    
    public void setVDeliveryTime(Integer VDeliveryTime) {
        this.VDeliveryTime = VDeliveryTime;
    }
    public Integer getVQuantity() {
        return this.VQuantity;
    }
    
    public void setVQuantity(Integer VQuantity) {
        this.VQuantity = VQuantity;
    }
    public Integer getVQuantityWarnLevel() {
        return this.VQuantityWarnLevel;
    }
    
    public void setVQuantityWarnLevel(Integer VQuantityWarnLevel) {
        this.VQuantityWarnLevel = VQuantityWarnLevel;
    }
    public Serializable getVDesc1() {
        return this.VDesc1;
    }
    
    public void setVDesc1(Serializable VDesc1) {
        this.VDesc1 = VDesc1;
    }
    public Serializable getVDesc2() {
        return this.VDesc2;
    }
    
    public void setVDesc2(Serializable VDesc2) {
        this.VDesc2 = VDesc2;
    }
    public Serializable getVDesc3() {
        return this.VDesc3;
    }
    
    public void setVDesc3(Serializable VDesc3) {
        this.VDesc3 = VDesc3;
    }
    public Serializable getVDesc4() {
        return this.VDesc4;
    }
    
    public void setVDesc4(Serializable VDesc4) {
        this.VDesc4 = VDesc4;
    }
    public Serializable getVDesc5() {
        return this.VDesc5;
    }
    
    public void setVDesc5(Serializable VDesc5) {
        this.VDesc5 = VDesc5;
    }
    public Serializable getVLive() {
        return this.VLive;
    }
    
    public void setVLive(Serializable VLive) {
        this.VLive = VLive;
    }
    public Serializable getVDownLoadInfo() {
        return this.VDownLoadInfo;
    }
    
    public void setVDownLoadInfo(Serializable VDownLoadInfo) {
        this.VDownLoadInfo = VDownLoadInfo;
    }
    public Serializable getVDownloadType() {
        return this.VDownloadType;
    }
    
    public void setVDownloadType(Serializable VDownloadType) {
        this.VDownloadType = VDownloadType;
    }
    public Integer getVOrderByValue() {
        return this.VOrderByValue;
    }
    
    public void setVOrderByValue(Integer VOrderByValue) {
        this.VOrderByValue = VOrderByValue;
    }
    public Double getVRrp() {
        return this.VRrp;
    }
    
    public void setVRrp(Double VRrp) {
        this.VRrp = VRrp;
    }
    public Serializable getVType() {
        return this.VType;
    }
    
    public void setVType(Serializable VType) {
        this.VType = VType;
    }
    public Integer getVCustomerGroupId() {
        return this.VCustomerGroupId;
    }
    
    public void setVCustomerGroupId(Integer VCustomerGroupId) {
        this.VCustomerGroupId = VCustomerGroupId;
    }




}


