package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * VersionSalesStats generated by hbm2java
 */
public class VersionSalesStats  implements java.io.Serializable {


     private int vssId;
     private Integer vssVersionId;
     private Integer vssQuantity;
     private Date vssDate;
     private Serializable vssIp;

    public VersionSalesStats() {
    }

	
    public VersionSalesStats(int vssId) {
        this.vssId = vssId;
    }
    public VersionSalesStats(int vssId, Integer vssVersionId, Integer vssQuantity, Date vssDate, Serializable vssIp) {
       this.vssId = vssId;
       this.vssVersionId = vssVersionId;
       this.vssQuantity = vssQuantity;
       this.vssDate = vssDate;
       this.vssIp = vssIp;
    }
   
    public int getVssId() {
        return this.vssId;
    }
    
    public void setVssId(int vssId) {
        this.vssId = vssId;
    }
    public Integer getVssVersionId() {
        return this.vssVersionId;
    }
    
    public void setVssVersionId(Integer vssVersionId) {
        this.vssVersionId = vssVersionId;
    }
    public Integer getVssQuantity() {
        return this.vssQuantity;
    }
    
    public void setVssQuantity(Integer vssQuantity) {
        this.vssQuantity = vssQuantity;
    }
    public Date getVssDate() {
        return this.vssDate;
    }
    
    public void setVssDate(Date vssDate) {
        this.vssDate = vssDate;
    }
    public Serializable getVssIp() {
        return this.vssIp;
    }
    
    public void setVssIp(Serializable vssIp) {
        this.vssIp = vssIp;
    }




}


