package model.utils;
// Generated Mar 16, 2017 4:57:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * WishList generated by hbm2java
 */
public class WishList  implements java.io.Serializable {


     private int wlId;
     private Integer wlCustomerId;
     private Serializable wlOwnerName;
     private Serializable wlName;
     private Serializable wlPublicPassword;
     private Serializable wlMessage;
     private Serializable wlItems;
     private Serializable wlQuantity;
     private Serializable wlOptionGroups;
     private Serializable wlOptions;
     private Serializable wlOrigItems;
     private Serializable wlOrigQuantity;
     private Serializable wlOrigOptionGroups;
     private Serializable wlOrigOptions;
     private Date wlDateTime;

    public WishList() {
    }

	
    public WishList(int wlId) {
        this.wlId = wlId;
    }
    public WishList(int wlId, Integer wlCustomerId, Serializable wlOwnerName, Serializable wlName, Serializable wlPublicPassword, Serializable wlMessage, Serializable wlItems, Serializable wlQuantity, Serializable wlOptionGroups, Serializable wlOptions, Serializable wlOrigItems, Serializable wlOrigQuantity, Serializable wlOrigOptionGroups, Serializable wlOrigOptions, Date wlDateTime) {
       this.wlId = wlId;
       this.wlCustomerId = wlCustomerId;
       this.wlOwnerName = wlOwnerName;
       this.wlName = wlName;
       this.wlPublicPassword = wlPublicPassword;
       this.wlMessage = wlMessage;
       this.wlItems = wlItems;
       this.wlQuantity = wlQuantity;
       this.wlOptionGroups = wlOptionGroups;
       this.wlOptions = wlOptions;
       this.wlOrigItems = wlOrigItems;
       this.wlOrigQuantity = wlOrigQuantity;
       this.wlOrigOptionGroups = wlOrigOptionGroups;
       this.wlOrigOptions = wlOrigOptions;
       this.wlDateTime = wlDateTime;
    }
   
    public int getWlId() {
        return this.wlId;
    }
    
    public void setWlId(int wlId) {
        this.wlId = wlId;
    }
    public Integer getWlCustomerId() {
        return this.wlCustomerId;
    }
    
    public void setWlCustomerId(Integer wlCustomerId) {
        this.wlCustomerId = wlCustomerId;
    }
    public Serializable getWlOwnerName() {
        return this.wlOwnerName;
    }
    
    public void setWlOwnerName(Serializable wlOwnerName) {
        this.wlOwnerName = wlOwnerName;
    }
    public Serializable getWlName() {
        return this.wlName;
    }
    
    public void setWlName(Serializable wlName) {
        this.wlName = wlName;
    }
    public Serializable getWlPublicPassword() {
        return this.wlPublicPassword;
    }
    
    public void setWlPublicPassword(Serializable wlPublicPassword) {
        this.wlPublicPassword = wlPublicPassword;
    }
    public Serializable getWlMessage() {
        return this.wlMessage;
    }
    
    public void setWlMessage(Serializable wlMessage) {
        this.wlMessage = wlMessage;
    }
    public Serializable getWlItems() {
        return this.wlItems;
    }
    
    public void setWlItems(Serializable wlItems) {
        this.wlItems = wlItems;
    }
    public Serializable getWlQuantity() {
        return this.wlQuantity;
    }
    
    public void setWlQuantity(Serializable wlQuantity) {
        this.wlQuantity = wlQuantity;
    }
    public Serializable getWlOptionGroups() {
        return this.wlOptionGroups;
    }
    
    public void setWlOptionGroups(Serializable wlOptionGroups) {
        this.wlOptionGroups = wlOptionGroups;
    }
    public Serializable getWlOptions() {
        return this.wlOptions;
    }
    
    public void setWlOptions(Serializable wlOptions) {
        this.wlOptions = wlOptions;
    }
    public Serializable getWlOrigItems() {
        return this.wlOrigItems;
    }
    
    public void setWlOrigItems(Serializable wlOrigItems) {
        this.wlOrigItems = wlOrigItems;
    }
    public Serializable getWlOrigQuantity() {
        return this.wlOrigQuantity;
    }
    
    public void setWlOrigQuantity(Serializable wlOrigQuantity) {
        this.wlOrigQuantity = wlOrigQuantity;
    }
    public Serializable getWlOrigOptionGroups() {
        return this.wlOrigOptionGroups;
    }
    
    public void setWlOrigOptionGroups(Serializable wlOrigOptionGroups) {
        this.wlOrigOptionGroups = wlOrigOptionGroups;
    }
    public Serializable getWlOrigOptions() {
        return this.wlOrigOptions;
    }
    
    public void setWlOrigOptions(Serializable wlOrigOptions) {
        this.wlOrigOptions = wlOrigOptions;
    }
    public Date getWlDateTime() {
        return this.wlDateTime;
    }
    
    public void setWlDateTime(Date wlDateTime) {
        this.wlDateTime = wlDateTime;
    }




}


