package models;
// Generated Mar 29, 2017 4:38:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Customerdemographics generated by hbm2java
 */
public class Customerdemographics  implements java.io.Serializable {


     private String customerTypeId;
     private String customerDesc;
     private Set customerses = new HashSet(0);

    public Customerdemographics() {
    }

	
    public Customerdemographics(String customerTypeId) {
        this.customerTypeId = customerTypeId;
    }
    public Customerdemographics(String customerTypeId, String customerDesc, Set customerses) {
       this.customerTypeId = customerTypeId;
       this.customerDesc = customerDesc;
       this.customerses = customerses;
    }
   
    public String getCustomerTypeId() {
        return this.customerTypeId;
    }
    
    public void setCustomerTypeId(String customerTypeId) {
        this.customerTypeId = customerTypeId;
    }
    public String getCustomerDesc() {
        return this.customerDesc;
    }
    
    public void setCustomerDesc(String customerDesc) {
        this.customerDesc = customerDesc;
    }
    public Set getCustomerses() {
        return this.customerses;
    }
    
    public void setCustomerses(Set customerses) {
        this.customerses = customerses;
    }




}


