package models;
// Generated Mar 29, 2017 4:38:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employees generated by hbm2java
 */
public class Employees  implements java.io.Serializable {


     private Integer employeeId;
     private Employees employees;
     private String lastName;
     private String firstName;
     private String title;
     private String titleOfCourtesy;
     private Date birthDate;
     private Date hireDate;
     private String address;
     private String city;
     private String region;
     private String postalCode;
     private String country;
     private String homePhone;
     private String extension;
     private byte[] photo;
     private String notes;
     private String photoPath;
     private Float salary;
     private Set territorieses = new HashSet(0);
     private Set orderses = new HashSet(0);
     private Set employeeses = new HashSet(0);

    public Employees() {
    }

	
    public Employees(String lastName, String firstName, String notes) {
        this.lastName = lastName;
        this.firstName = firstName;
        this.notes = notes;
    }
    public Employees(Employees employees, String lastName, String firstName, String title, String titleOfCourtesy, Date birthDate, Date hireDate, String address, String city, String region, String postalCode, String country, String homePhone, String extension, byte[] photo, String notes, String photoPath, Float salary, Set territorieses, Set orderses, Set employeeses) {
       this.employees = employees;
       this.lastName = lastName;
       this.firstName = firstName;
       this.title = title;
       this.titleOfCourtesy = titleOfCourtesy;
       this.birthDate = birthDate;
       this.hireDate = hireDate;
       this.address = address;
       this.city = city;
       this.region = region;
       this.postalCode = postalCode;
       this.country = country;
       this.homePhone = homePhone;
       this.extension = extension;
       this.photo = photo;
       this.notes = notes;
       this.photoPath = photoPath;
       this.salary = salary;
       this.territorieses = territorieses;
       this.orderses = orderses;
       this.employeeses = employeeses;
    }
   
    public Integer getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getTitleOfCourtesy() {
        return this.titleOfCourtesy;
    }
    
    public void setTitleOfCourtesy(String titleOfCourtesy) {
        this.titleOfCourtesy = titleOfCourtesy;
    }
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
    public Date getHireDate() {
        return this.hireDate;
    }
    
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getHomePhone() {
        return this.homePhone;
    }
    
    public void setHomePhone(String homePhone) {
        this.homePhone = homePhone;
    }
    public String getExtension() {
        return this.extension;
    }
    
    public void setExtension(String extension) {
        this.extension = extension;
    }
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public String getPhotoPath() {
        return this.photoPath;
    }
    
    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath;
    }
    public Float getSalary() {
        return this.salary;
    }
    
    public void setSalary(Float salary) {
        this.salary = salary;
    }
    public Set getTerritorieses() {
        return this.territorieses;
    }
    
    public void setTerritorieses(Set territorieses) {
        this.territorieses = territorieses;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }
    public Set getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set employeeses) {
        this.employeeses = employeeses;
    }




}


