package models;
// Generated Mar 29, 2017 4:38:48 PM by Hibernate Tools 4.3.1



/**
 * OrderdetailsId generated by hbm2java
 */
public class OrderdetailsId  implements java.io.Serializable {


     private int orderId;
     private int productId;

    public OrderdetailsId() {
    }

    public OrderdetailsId(int orderId, int productId) {
       this.orderId = orderId;
       this.productId = productId;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderdetailsId) ) return false;
		 OrderdetailsId castOther = ( OrderdetailsId ) other; 
         
		 return (this.getOrderId()==castOther.getOrderId())
 && (this.getProductId()==castOther.getProductId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrderId();
         result = 37 * result + this.getProductId();
         return result;
   }   


}


