package models;
// Generated Mar 29, 2017 4:38:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Shippers generated by hbm2java
 */
public class Shippers  implements java.io.Serializable {


     private Integer shipperId;
     private String companyName;
     private String phone;
     private Set orderses = new HashSet(0);

    public Shippers() {
    }

	
    public Shippers(String companyName) {
        this.companyName = companyName;
    }
    public Shippers(String companyName, String phone, Set orderses) {
       this.companyName = companyName;
       this.phone = phone;
       this.orderses = orderses;
    }
   
    public Integer getShipperId() {
        return this.shipperId;
    }
    
    public void setShipperId(Integer shipperId) {
        this.shipperId = shipperId;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


